//! Part hierarchy panel for explicit asset recipes.

#![allow(dead_code)]

use std::collections::{BTreeMap, BTreeSet};

use egui::RichText;

use crate::asset::{
    AssetAppCommand, AssetPart, AssetUiState, GeneratedPartKind, PartDefinitionId, PartInstanceId,
};

/// Stable flattened row consumed by the part tree UI and tests.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct PartTreeRow {
    pub part: PartInstanceId,
    pub depth: usize,
    pub name: String,
    pub definition: PartDefinitionId,
    pub definition_name: String,
    pub selected: bool,
    pub enabled: bool,
    pub optional: bool,
    pub shared_definition: bool,
    pub generated_label: Option<String>,
    pub validation_badge: Option<String>,
    pub socket_count: usize,
    pub region_count: usize,
}

/// Draw the named part hierarchy and emit selection commands.
pub(crate) fn show(ui: &mut egui::Ui, state: &AssetUiState) -> Vec<AssetAppCommand> {
    let mut commands = Vec::new();
    ui.heading("Parts");

    let rows = build_part_tree_rows(state);
    if rows.is_empty() {
        ui.weak(empty_part_tree_message());
        return commands;
    }

    for row in rows {
        ui.horizontal(|ui| {
            ui.add_space(row.depth as f32 * 14.0);
            let name = if row.enabled {
                RichText::new(&row.name)
            } else {
                RichText::new(&row.name).weak()
            };
            let response = ui
                .selectable_label(row.selected, name)
                .on_hover_text(format!(
                    "Instance {} | Definition {}",
                    row.part.0, row.definition.0
                ));
            if response.clicked() {
                commands.extend(select_part_command(state.selected_part, row.part));
            }
            if row.shared_definition {
                ui.small("Shared")
                    .on_hover_text(format!("Shared definition: {}", row.definition_name));
            }
            if row.optional {
                let label = if row.enabled {
                    "Optional"
                } else {
                    "Optional off"
                };
                ui.small(label).on_hover_text("Authored optional part.");
            }
            if let Some(label) = &row.generated_label {
                ui.small(label)
                    .on_hover_text("Generated by a mirror or array operation.");
            }
            if row.socket_count > 0 {
                ui.small(format!("{} sockets", row.socket_count));
            }
            if let Some(badge) = &row.validation_badge {
                ui.colored_label(ui.visuals().warn_fg_color, badge)
                    .on_hover_text("Validation warning for this part.");
            }
        });
    }
    commands
}

/// Build deterministic rows for a parent-child part hierarchy.
#[must_use]
pub(crate) fn build_part_tree_rows(state: &AssetUiState) -> Vec<PartTreeRow> {
    let definition_use_counts = state.definition_use_counts();
    let mut children = BTreeMap::<Option<PartInstanceId>, Vec<&AssetPart>>::new();
    for part in &state.parts {
        children.entry(part.parent).or_default().push(part);
    }
    for items in children.values_mut() {
        items.sort_by_key(|part| (part.name.clone(), part.id));
    }

    let mut rows = Vec::new();
    let mut visited = BTreeSet::new();
    append_child_rows(
        None,
        0,
        state,
        &children,
        &definition_use_counts,
        &mut visited,
        &mut rows,
    );

    for part in &state.parts {
        if !visited.contains(&part.id) {
            append_part_row(
                part,
                0,
                state,
                &definition_use_counts,
                &mut visited,
                &mut rows,
            );
        }
    }

    rows
}

/// Emit a selection only when the requested part is not already selected.
#[must_use]
pub(crate) fn select_part_command(
    current: Option<PartInstanceId>,
    selected: PartInstanceId,
) -> Option<AssetAppCommand> {
    (current != Some(selected)).then_some(AssetAppCommand::SelectPart(selected))
}

/// Empty-state copy for tests and the UI.
#[must_use]
pub(crate) fn empty_part_tree_message() -> &'static str {
    "No asset parts are available yet."
}

fn append_child_rows(
    parent: Option<PartInstanceId>,
    depth: usize,
    state: &AssetUiState,
    children: &BTreeMap<Option<PartInstanceId>, Vec<&AssetPart>>,
    definition_use_counts: &BTreeMap<PartDefinitionId, usize>,
    visited: &mut BTreeSet<PartInstanceId>,
    rows: &mut Vec<PartTreeRow>,
) {
    let Some(items) = children.get(&parent) else {
        return;
    };
    for part in items {
        if append_part_row(part, depth, state, definition_use_counts, visited, rows) {
            append_child_rows(
                Some(part.id),
                depth + 1,
                state,
                children,
                definition_use_counts,
                visited,
                rows,
            );
        }
    }
}

fn append_part_row(
    part: &AssetPart,
    depth: usize,
    state: &AssetUiState,
    definition_use_counts: &BTreeMap<PartDefinitionId, usize>,
    visited: &mut BTreeSet<PartInstanceId>,
    rows: &mut Vec<PartTreeRow>,
) -> bool {
    if !visited.insert(part.id) {
        return false;
    }

    rows.push(PartTreeRow {
        part: part.id,
        depth,
        name: part.name.clone(),
        definition: part.definition,
        definition_name: part.definition_name.clone(),
        selected: state.selected_part == Some(part.id),
        enabled: part.enabled,
        optional: part.optional,
        shared_definition: definition_use_counts
            .get(&part.definition)
            .is_some_and(|count| *count > 1),
        generated_label: generated_label(&part.generated),
        validation_badge: (part.warning_count > 0).then(|| format!("{}!", part.warning_count)),
        socket_count: part.socket_count,
        region_count: part.region_count,
    });
    true
}

fn generated_label(kind: &GeneratedPartKind) -> Option<String> {
    kind.label()
}
