/// Return the deterministic Blender reconstruction helper written into packages.
#[must_use]
pub fn blender_reconstruction_script() -> &'static str {
    r####"# Generated by Shape Lab explicit model export.
import argparse
import json
import math
from pathlib import Path
import struct
import sys
import types

MAGIC = b"SLABPARTMESH1\0"
NONE_U64 = (1 << 64) - 1


def build_stub_bpy():
    module = types.SimpleNamespace()

    class Vertex:
        def __init__(self, co):
            self.co = tuple(co)

    class Mesh:
        def __init__(self, name):
            self.name = name
            self.vertices = []
            self.polygons = []
            self.loops = []
            self.custom_normals = []

        def from_pydata(self, positions, _edges, faces):
            self.vertices = [Vertex(position) for position in positions]
            self.polygons = [tuple(face) for face in faces]
            self.loops = [None for face in faces for _ in face]

        def update(self, calc_edges=True):
            return None

        def normals_split_custom_set(self, normals):
            self.custom_normals = [tuple(normal) for normal in normals]

    class Meshes(dict):
        def new(self, name):
            mesh = Mesh(name)
            self[name] = mesh
            return mesh

    class Object(dict):
        def __init__(self, name, mesh):
            super().__init__()
            self.name = name
            self.data = mesh
            self.location = (0.0, 0.0, 0.0)
            self.parent = None

    class Objects(dict):
        def new(self, name, mesh):
            return Object(name, mesh)

    class CollectionObjects:
        def link(self, obj):
            module.data.objects[obj.name] = obj

    class ObjectOps:
        def select_all(self, action="SELECT"):
            return None

        def delete(self):
            module.data.objects.clear()
            module.data.meshes.clear()

    class WmOps:
        def save_as_mainfile(self, filepath):
            Path(filepath).write_text("stub blend\n", encoding="utf-8")

        def open_mainfile(self, filepath):
            if not Path(filepath).exists():
                raise RuntimeError(f"missing blend file: {filepath}")

    module.data = types.SimpleNamespace(meshes=Meshes(), objects=Objects())
    module.context = types.SimpleNamespace(
        collection=types.SimpleNamespace(objects=CollectionObjects())
    )
    module.ops = types.SimpleNamespace(object=ObjectOps(), wm=WmOps())
    return module


try:
    import bpy  # type: ignore
except ModuleNotFoundError:
    bpy = build_stub_bpy()


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--package-dir", default=str(Path(__file__).resolve().parent))
    parser.add_argument("--out-dir", default=None)
    parser.add_argument("--verify-reopen", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = sys.argv[1:]
    if "--" in args:
        args = args[args.index("--") + 1 :]
    return parser.parse_args(args)


def read_u8(data, offset):
    if offset + 1 > len(data):
        raise ValueError("meshbin payload is truncated")
    return data[offset], offset + 1


def read_u32(data, offset):
    if offset + 4 > len(data):
        raise ValueError("meshbin payload is truncated")
    return struct.unpack_from("<I", data, offset)[0], offset + 4


def read_u64(data, offset):
    if offset + 8 > len(data):
        raise ValueError("meshbin payload is truncated")
    return struct.unpack_from("<Q", data, offset)[0], offset + 8


def read_f32(data, offset):
    if offset + 4 > len(data):
        raise ValueError("meshbin payload is truncated")
    return struct.unpack_from("<f", data, offset)[0], offset + 4


def option_u64(value):
    return None if value == NONE_U64 else value


def package_path(root, relative):
    path = Path(relative)
    if path.is_absolute() or ".." in path.parts or not path.parts:
        raise ValueError(f"unsafe package-relative path: {relative}")
    resolved_root = root.resolve()
    resolved = (root / path).resolve()
    if resolved_root not in (resolved, *resolved.parents):
        raise ValueError(f"package path escapes root: {relative}")
    return resolved


def read_part_meshbin(path):
    data = path.read_bytes()
    if not data.startswith(MAGIC):
        raise ValueError(f"unsupported part meshbin magic: {path}")
    offset = len(MAGIC)
    version, offset = read_u32(data, offset)
    if version != 1:
        raise ValueError(f"unsupported part meshbin version: {version}")
    definition_id, offset = read_u64(data, offset)
    instance_id, offset = read_u64(data, offset)
    prototype_instance_id, offset = read_u64(data, offset)
    generated_by, offset = read_u64(data, offset)
    source_recipe_instance, offset = read_u8(data, offset)
    vertex_count, offset = read_u64(data, offset)
    face_count, offset = read_u64(data, offset)
    index_count, offset = read_u64(data, offset)
    normal_count, offset = read_u64(data, offset)

    positions = []
    for _ in range(vertex_count):
        x, offset = read_f32(data, offset)
        y, offset = read_f32(data, offset)
        z, offset = read_f32(data, offset)
        positions.append((x, y, z))
    vertex_ids = []
    for _ in range(vertex_count):
        value, offset = read_u64(data, offset)
        vertex_ids.append(value)
    face_counts = []
    for _ in range(face_count):
        value, offset = read_u32(data, offset)
        face_counts.append(value)
    polygon_indices = []
    for _ in range(index_count):
        value, offset = read_u32(data, offset)
        polygon_indices.append(value)
    loop_normals = []
    for _ in range(normal_count):
        x, offset = read_f32(data, offset)
        y, offset = read_f32(data, offset)
        z, offset = read_f32(data, offset)
        loop_normals.append((x, y, z))
    face_region_ids = []
    for _ in range(face_count):
        value, offset = read_u64(data, offset)
        face_region_ids.append(option_u64(value))
    face_element_ids = []
    for _ in range(face_count):
        value, offset = read_u64(data, offset)
        face_element_ids.append(value)
    if offset != len(data):
        raise ValueError(f"part meshbin has trailing bytes: {path}")

    faces = []
    cursor = 0
    for count in face_counts:
        if count < 3:
            raise ValueError(f"degenerate polygon in {path}")
        face = polygon_indices[cursor : cursor + count]
        cursor += count
        if len(face) != count:
            raise ValueError(f"polygon index payload is truncated in {path}")
        if any(index >= vertex_count for index in face):
            raise ValueError(f"polygon index out of range in {path}")
        faces.append(face)
    if cursor != len(polygon_indices):
        raise ValueError(f"polygon face counts do not consume all indices in {path}")
    if len(loop_normals) != len(polygon_indices):
        raise ValueError(f"split normal count does not match loop count in {path}")
    for point in [*positions, *loop_normals]:
        if not all(math.isfinite(component) for component in point):
            raise ValueError(f"non-finite numeric payload in {path}")

    return {
        "definition_id": definition_id,
        "instance_id": instance_id,
        "prototype_instance_id": option_u64(prototype_instance_id),
        "generated_by": option_u64(generated_by),
        "source_recipe_instance": bool(source_recipe_instance),
        "positions": positions,
        "vertex_ids": vertex_ids,
        "faces": faces,
        "loop_normals": loop_normals,
        "face_region_ids": face_region_ids,
        "face_element_ids": face_element_ids,
    }


def load_package(root):
    manifest = json.loads(package_path(root, "asset-manifest.json").read_text(encoding="utf-8"))
    parts = []
    for part_manifest in manifest["parts"]:
        mesh = read_part_meshbin(package_path(root, part_manifest["mesh"]))
        parts.append({"manifest": part_manifest, "mesh": mesh})
    return manifest, parts


def validate_created_object(obj, part):
    mesh_payload = part["mesh"]
    if len(obj.data.polygons) != len(mesh_payload["faces"]):
        raise RuntimeError(f"topology mismatch in {obj.name}")
    if len(obj.data.vertices) != len(mesh_payload["positions"]):
        raise RuntimeError(f"vertex count mismatch in {obj.name}")
    if obj.get("shape_lab_instance_id") != mesh_payload["instance_id"]:
        raise RuntimeError(f"semantic ID mismatch in {obj.name}")


def create_scene(parts):
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete()
    objects_by_id = {}
    pending_parents = []
    for part in parts:
        part_manifest = part["manifest"]
        mesh_payload = part["mesh"]
        pivot = tuple(float(value) for value in part_manifest.get("pivot_origin", (0.0, 0.0, 0.0)))
        local_positions = [
            (position[0] - pivot[0], position[1] - pivot[1], position[2] - pivot[2])
            for position in mesh_payload["positions"]
        ]
        mesh = bpy.data.meshes.new(part_manifest["object_name"] + "_mesh")
        mesh.from_pydata(local_positions, [], mesh_payload["faces"])
        mesh.update(calc_edges=True)
        if hasattr(mesh, "normals_split_custom_set"):
            try:
                mesh.normals_split_custom_set(mesh_payload["loop_normals"])
            except Exception as exc:
                print(f"split normal assignment skipped for {part_manifest['object_name']}: {exc}")
        obj = bpy.data.objects.new(part_manifest["object_name"], mesh)
        obj.location = pivot
        obj["shape_lab_instance_id"] = mesh_payload["instance_id"]
        obj["shape_lab_definition_id"] = mesh_payload["definition_id"]
        if mesh_payload["prototype_instance_id"] is not None:
            obj["shape_lab_prototype_instance_id"] = mesh_payload["prototype_instance_id"]
        if mesh_payload["generated_by"] is not None:
            obj["shape_lab_generated_by"] = mesh_payload["generated_by"]
        obj["shape_lab_regions"] = json.dumps(part_manifest.get("regions", []), sort_keys=True)
        bpy.context.collection.objects.link(obj)
        validate_created_object(obj, part)
        objects_by_id[mesh_payload["instance_id"]] = obj
        pending_parents.append((obj, part_manifest.get("parent_instance_id")))
    for obj, parent_id in pending_parents:
        if parent_id is not None and parent_id in objects_by_id:
            obj.parent = objects_by_id[parent_id]
    return objects_by_id


def verify_reopen(path, parts):
    bpy.ops.wm.open_mainfile(filepath=str(path))
    for part in parts:
        name = part["manifest"]["object_name"]
        obj = bpy.data.objects.get(name)
        if obj is None:
            raise RuntimeError(f"missing object after reopen: {name}")
        validate_created_object(obj, part)


def main():
    args = parse_args()
    package_root = Path(args.package_dir)
    out_dir = Path(args.out_dir) if args.out_dir is not None else package_root
    manifest, parts = load_package(package_root)
    create_scene(parts)
    blend_path = out_dir / "reconstructed.blend"
    if not args.dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)
        bpy.ops.wm.save_as_mainfile(filepath=str(blend_path))
        if args.verify_reopen:
            verify_reopen(blend_path, parts)
    print(
        json.dumps(
            {
                "objects": len(parts),
                "schema_version": manifest["schema_version"],
                "blend": str(blend_path),
                "verify_reopen": bool(args.verify_reopen and not args.dry_run),
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
"####
}
