
/// Declared attachment socket on a part.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SocketSpec {
    /// Stable socket ID.
    pub id: SocketId,
    /// Human-facing socket name.
    pub name: String,
    /// Socket frame in part-local coordinates.
    pub local_frame: Frame3,
    /// Generic socket role.
    pub role: String,
    /// Free-form semantic tags.
    pub tags: BTreeSet<String>,
}

/// Attachment relation for a child instance.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AttachmentSpec {
    /// Parent instance used for the attachment.
    pub parent_instance: PartInstanceId,
    /// Socket on the parent definition.
    pub parent_socket: SocketId,
    /// Socket on the child definition.
    pub child_socket: SocketId,
    /// Offset applied after socket alignment.
    pub local_offset: Transform3,
    /// Attachment mode.
    pub mode: AttachmentMode,
}

/// Attachment implementation mode.
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum AttachmentMode {
    /// Keep child and parent as rigid separate parts.
    RigidSeparate,
    /// Reserved future boundary welding mode.
    WeldBoundaryReserved,
}

/// Declared surface region.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SurfaceRegionSpec {
    /// Stable region ID.
    pub id: RegionId,
    /// Human-facing region name.
    pub name: String,
    /// Generic region role.
    pub role: SurfaceRole,
    /// Free-form semantic tags.
    pub tags: BTreeSet<String>,
}

/// Generic role for a semantic surface region.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum SurfaceRole {
    /// Primary visible surface.
    PrimarySurface,
    /// Cap surface.
    Cap,
    /// Side surface.
    Side,
    /// Bevel band surface.
    BevelBand,
    /// Panel surface.
    Panel,
    /// Rim or border around an opening or recess.
    Rim,
    /// Wall generated by a cut operation.
    CutWall,
    /// Trim surface.
    Trim,
    /// Attachment surface.
    Attachment,
    /// Interior surface.
    Interior,
    /// Detail surface.
    Detail,
    /// Custom generic role.
    Custom(String),
}

/// Editable scalar parameter descriptor.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ParameterDescriptor {
    /// Stable parameter ID.
    pub id: ParameterId,
    /// Canonical scalar path.
    pub path: String,
    /// Human-facing label.
    pub label: String,
    /// Human-facing parameter group.
    pub group: String,
    /// Minimum permitted scalar.
    pub minimum: f32,
    /// Maximum permitted scalar.
    pub maximum: f32,
    /// Suggested UI step.
    pub step: f32,
    /// Standard deviation for deterministic mutation.
    pub mutation_sigma: f32,
    /// Whether changing this parameter can change topology.
    pub topology_changing: bool,
    /// Beginner-facing explanation.
    pub beginner_description: String,
}

/// Asset-level constraint placeholder.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AssetConstraint {
    /// Require an instance to remain present.
    RequireInstance {
        /// Required instance.
        instance: PartInstanceId,
    },
    /// Prevent two semantic tags from coexisting.
    MutuallyExclusiveTags {
        /// First tag.
        first: String,
        /// Second tag.
        second: String,
    },
    /// Reserved custom constraint identified by stable code.
    Custom {
        /// Stable constraint code.
        code: String,
        /// Human-readable message.
        message: String,
    },
}

/// A semantic endpoint used by authored relationship policies.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum AssetPartSelector {
    /// One concrete source recipe instance.
    SpecificInstance {
        /// Selected instance.
        instance: PartInstanceId,
    },
    /// All generated occurrences produced by one modeling operation.
    GeneratedByOperation {
        /// Generator operation.
        operation: OperationId,
    },
    /// A source instance and every generated occurrence that names it as prototype.
    PrototypeAndGeneratedOccurrences {
        /// Source prototype instance.
        prototype: PartInstanceId,
    },
    /// Every occurrence whose part definition carries the tag.
    PartTag {
        /// Required definition tag.
        tag: String,
    },
    /// Every occurrence whose part definition carries the role tag.
    DefinitionRole {
        /// Required definition role.
        role: String,
    },
}

impl AssetPartSelector {
    /// Select one concrete source recipe instance.
    #[must_use]
    pub fn specific(instance: PartInstanceId) -> Self {
        Self::SpecificInstance { instance }
    }
}

#[derive(Deserialize)]
#[serde(untagged)]
enum AssetPartSelectorWire {
    Selector(AssetPartSelector),
    LegacyInstance(PartInstanceId),
}

impl From<AssetPartSelectorWire> for AssetPartSelector {
    fn from(value: AssetPartSelectorWire) -> Self {
        match value {
            AssetPartSelectorWire::Selector(selector) => selector,
            AssetPartSelectorWire::LegacyInstance(instance) => {
                AssetPartSelector::specific(instance)
            }
        }
    }
}

/// How relationship selector results should be paired before validation.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelationshipPairing {
    /// Apply the relationship to every resolved pair.
    #[default]
    AllPairs,
    /// Pair resolved selectors by deterministic occurrence order.
    ByOccurrenceIndex,
    /// Pair occurrences that share the same source prototype lineage.
    ByPrototypeLineage,
    /// Greedily pair each left occurrence with the nearest unpaired right occurrence.
    NearestOneToOne,
    /// Use explicitly authored concrete occurrence pairs.
    Explicit(Vec<(PartInstanceId, PartInstanceId)>),
}

impl RelationshipPairing {
    fn is_all_pairs(&self) -> bool {
        matches!(self, Self::AllPairs)
    }
}

/// Authored geometric relationship policy between semantic part selectors.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub enum AssetRelationshipPolicy {
    /// This pair is intentionally allowed to overlap.
    MayOverlap {
        /// First selector.
        first: AssetPartSelector,
        /// Second selector.
        second: AssetPartSelector,
        /// Pairing mode for selector results.
        #[serde(default, skip_serializing_if = "RelationshipPairing::is_all_pairs")]
        pairing: RelationshipPairing,
        /// Human-facing reason for the relationship.
        reason: String,
    },
    /// This pair must not intersect.
    MustNotIntersect {
        /// First selector.
        first: AssetPartSelector,
        /// Second selector.
        second: AssetPartSelector,
        /// Pairing mode for selector results.
        #[serde(default, skip_serializing_if = "RelationshipPairing::is_all_pairs")]
        pairing: RelationshipPairing,
    },
    /// This pair must touch or remain within attachment clearance.
    MustTouch {
        /// First selector.
        first: AssetPartSelector,
        /// Second selector.
        second: AssetPartSelector,
        /// Pairing mode for selector results.
        #[serde(default, skip_serializing_if = "RelationshipPairing::is_all_pairs")]
        pairing: RelationshipPairing,
        /// Maximum accepted clearance in world units.
        max_clearance: f32,
    },
    /// The contained part must remain inside the container's authored bounds.
    MustContain {
        /// Containing selector.
        container: AssetPartSelector,
        /// Contained selector.
        contained: AssetPartSelector,
        /// Pairing mode for selector results.
        #[serde(default, skip_serializing_if = "RelationshipPairing::is_all_pairs")]
        pairing: RelationshipPairing,
    },
    /// This pair must maintain at least the authored clearance.
    MinimumClearance {
        /// First selector.
        first: AssetPartSelector,
        /// Second selector.
        second: AssetPartSelector,
        /// Pairing mode for selector results.
        #[serde(default, skip_serializing_if = "RelationshipPairing::is_all_pairs")]
        pairing: RelationshipPairing,
        /// Minimum clearance in world units.
        clearance: f32,
    },
    /// The child selector must remain attached to the parent selector through named sockets.
    SocketAttached {
        /// Parent selector.
        parent: AssetPartSelector,
        /// Child selector.
        child: AssetPartSelector,
        /// Pairing mode for selector results.
        #[serde(default, skip_serializing_if = "RelationshipPairing::is_all_pairs")]
        pairing: RelationshipPairing,
        /// Socket on the parent part.
        parent_socket: SocketId,
        /// Socket on the child part.
        child_socket: SocketId,
        /// Maximum accepted socket-origin distance in world units.
        max_origin_distance: f32,
        /// Maximum accepted axis angle in degrees.
        max_axis_angle_degrees: f32,
        /// Optional maximum accepted mesh clearance in world units.
        max_clearance: Option<f32>,
    },
}

impl AssetRelationshipPolicy {
    /// Create a relationship that allows intentional overlap.
    #[must_use]
    pub fn may_overlap(
        first: PartInstanceId,
        second: PartInstanceId,
        reason: impl Into<String>,
    ) -> Self {
        Self::MayOverlap {
            first: AssetPartSelector::specific(first),
            second: AssetPartSelector::specific(second),
            pairing: RelationshipPairing::AllPairs,
            reason: reason.into(),
        }
    }
}

#[derive(Deserialize)]
enum AssetRelationshipPolicyWire {
    MayOverlap {
        first: AssetPartSelectorWire,
        second: AssetPartSelectorWire,
        #[serde(default)]
        pairing: RelationshipPairing,
        reason: String,
    },
    MustNotIntersect {
        first: AssetPartSelectorWire,
        second: AssetPartSelectorWire,
        #[serde(default)]
        pairing: RelationshipPairing,
    },
    MustTouch {
        first: AssetPartSelectorWire,
        second: AssetPartSelectorWire,
        #[serde(default)]
        pairing: RelationshipPairing,
        max_clearance: f32,
    },
    MustContain {
        container: AssetPartSelectorWire,
        contained: AssetPartSelectorWire,
        #[serde(default)]
        pairing: RelationshipPairing,
    },
    MinimumClearance {
        first: AssetPartSelectorWire,
        second: AssetPartSelectorWire,
        #[serde(default)]
        pairing: RelationshipPairing,
        clearance: f32,
    },
    SocketAttached {
        parent: AssetPartSelectorWire,
        child: AssetPartSelectorWire,
        #[serde(default)]
        pairing: RelationshipPairing,
        parent_socket: Option<SocketId>,
        child_socket: Option<SocketId>,
        socket: Option<SocketId>,
        max_origin_distance: f32,
        max_axis_angle_degrees: f32,
        max_clearance: Option<f32>,
    },
}

impl AssetRelationshipPolicyWire {
    fn into_policy<E>(self) -> Result<AssetRelationshipPolicy, E>
    where
        E: de::Error,
    {
        Ok(match self {
            Self::MayOverlap {
                first,
                second,
                pairing,
                reason,
            } => AssetRelationshipPolicy::MayOverlap {
                first: first.into(),
                second: second.into(),
                pairing,
                reason,
            },
            Self::MustNotIntersect {
                first,
                second,
                pairing,
            } => AssetRelationshipPolicy::MustNotIntersect {
                first: first.into(),
                second: second.into(),
                pairing,
            },
            Self::MustTouch {
                first,
                second,
                pairing,
                max_clearance,
            } => AssetRelationshipPolicy::MustTouch {
                first: first.into(),
                second: second.into(),
                pairing,
                max_clearance,
            },
            Self::MustContain {
                container,
                contained,
                pairing,
            } => AssetRelationshipPolicy::MustContain {
                container: container.into(),
                contained: contained.into(),
                pairing,
            },
            Self::MinimumClearance {
                first,
                second,
                pairing,
                clearance,
            } => AssetRelationshipPolicy::MinimumClearance {
                first: first.into(),
                second: second.into(),
                pairing,
                clearance,
            },
            Self::SocketAttached {
                parent,
                child,
                pairing,
                parent_socket,
                child_socket,
                socket,
                max_origin_distance,
                max_axis_angle_degrees,
                max_clearance,
            } => {
                let parent_socket = parent_socket.or(socket).ok_or_else(|| {
                    E::custom("SocketAttached relationship is missing parent_socket")
                })?;
                let child_socket = child_socket.or(socket).ok_or_else(|| {
                    E::custom("SocketAttached relationship is missing child_socket")
                })?;
                AssetRelationshipPolicy::SocketAttached {
                    parent: parent.into(),
                    child: child.into(),
                    pairing,
                    parent_socket,
                    child_socket,
                    max_origin_distance,
                    max_axis_angle_degrees,
                    max_clearance,
                }
            }
        })
    }
}

impl<'de> Deserialize<'de> for AssetRelationshipPolicy {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        AssetRelationshipPolicyWire::deserialize(deserializer)?.into_policy()
    }
}
