//! Blender adapter contract for schema-3 packages.
//!
//! Schema 3 separates semantic evaluation from exact replay. The generated
//! Blender script treats cumulative baked positions files as the authority for
//! reconstruction, while semantic operators are checked only as validation.

use serde::{Deserialize, Serialize};

/// Options for generating a schema-3 Blender reconstruction script.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BlenderAdapterOptions {
    /// Package-relative manifest path used by the generated script.
    pub manifest_file: String,
    /// Report path for adapter verification output.
    pub report_file: String,
    /// Whether the script should verify an already-saved reconstruction.
    pub verify_existing: bool,
}

impl Default for BlenderAdapterOptions {
    fn default() -> Self {
        Self {
            manifest_file: "manifest.json".to_owned(),
            report_file: "blender-verification.json".to_owned(),
            verify_existing: false,
        }
    }
}

/// Builds a schema-3 Blender reconstruction script.
///
/// The generated script is standalone Python intended to run inside Blender.
/// It reconstructs editable shape keys and the baked object from cumulative
/// stage positions; native Blender deformers are never used as replay input.
pub fn blender_reconstruction_script_v3(options: &BlenderAdapterOptions) -> String {
    PYTHON_SCRIPT_V3
        .replace(
            "__SHAPELAB_MANIFEST_FILE__",
            &python_string_literal(&options.manifest_file),
        )
        .replace(
            "__SHAPELAB_REPORT_FILE__",
            &python_string_literal(&options.report_file),
        )
        .replace(
            "__SHAPELAB_VERIFY_EXISTING__",
            python_bool(options.verify_existing),
        )
}

fn python_string_literal(value: &str) -> String {
    serde_json::to_string(value).expect("JSON strings are valid Python string literals")
}

fn python_bool(value: bool) -> &'static str {
    if value { "True" } else { "False" }
}

const PYTHON_SCRIPT_V3: &str = r####"# Generated by Shape Lab's schema-3 deformation decompiler.
from pathlib import Path, PurePosixPath, PureWindowsPath
import argparse
import json
import math
import struct
import sys
import bpy

ROOT = Path(__file__).resolve().parent
SUPPORTED_SCHEMA_VERSION = 3
MANIFEST_FILE = __SHAPELAB_MANIFEST_FILE__
REPORT_FILE = __SHAPELAB_REPORT_FILE__
DEFAULT_VERIFY_EXISTING = __SHAPELAB_VERIFY_EXISTING__
SOURCE_OBJECT_NAME = "ShapeLab_V3_Decompiled"
BAKED_OBJECT_NAME = "ShapeLab_V3_Reconstructed_Baked"
VERTEX_ID_ATTRIBUTE = "shapelab_vertex_id"
FNV_OFFSET = 0xCBF29CE484222325
FNV_PRIME = 0x00000100000001B3
ROTATION_ORTHONORMAL_TOLERANCE = 1.0e-3
MIN_AXIS_LENGTH = 1.0e-6
IDENTITY_ANGLE_EPSILON = 1.0e-7


def command_line_arguments():
    parser = argparse.ArgumentParser(
        description="Reconstruct and verify a Shape Lab schema-3 package"
    )
    parser.add_argument(
        "--manifest",
        default=MANIFEST_FILE,
        help="schema-3 manifest path, relative to the package",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--verify-existing",
        dest="verify_existing",
        action="store_true",
        help="verify objects already stored in the opened .blend file",
    )
    mode.add_argument(
        "--reconstruct",
        dest="verify_existing",
        action="store_false",
        help="reconstruct objects from package sidecars",
    )
    parser.set_defaults(verify_existing=DEFAULT_VERIFY_EXISTING)
    parser.add_argument(
        "--output-blend",
        default="reconstructed.blend",
        help="output .blend path, relative to the package unless absolute",
    )
    parser.add_argument(
        "--report",
        default=REPORT_FILE,
        help="verification JSON path, relative to the package unless absolute",
    )
    parser.add_argument("--no-save", action="store_true", help="do not save a .blend file")
    argv = sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else sys.argv[1:]
    return parser.parse_args(argv)


def output_path(value):
    path = Path(value)
    return path if path.is_absolute() else ROOT / path


def is_finite_number(value):
    return (
        isinstance(value, (int, float))
        and not isinstance(value, bool)
        and math.isfinite(value)
    )


def require_mapping(value, label):
    if not isinstance(value, dict):
        raise ValueError(f"{label} must be an object")
    return value


def require_string(value, label, allow_empty=False):
    if not isinstance(value, str):
        raise ValueError(f"{label} must be a string")
    if not allow_empty and not value:
        raise ValueError(f"{label} must not be empty")
    return value


def require_bool(value, label):
    if not isinstance(value, bool):
        raise ValueError(f"{label} must be a boolean")
    return value


def require_nonnegative_int(value, label):
    if not isinstance(value, int) or isinstance(value, bool) or value < 0:
        raise ValueError(f"{label} must be a non-negative integer")
    return value


def require_finite_number(value, label):
    if not is_finite_number(value):
        raise ValueError(f"{label} must be finite")
    return value


def require_f32_list(value, length, label):
    if (
        not isinstance(value, list)
        or len(value) != length
        or not all(is_finite_number(component) for component in value)
    ):
        raise ValueError(f"{label} must contain {length} finite numbers")
    return [f32(component) for component in value]


def reject_package_asset_path(value):
    require_string(value, "package asset path")
    if "\x00" in value:
        raise ValueError(f"unsafe package-relative path: {value}")
    posix = PurePosixPath(value)
    windows = PureWindowsPath(value)
    if (
        posix.is_absolute()
        or windows.is_absolute()
        or bool(windows.drive)
        or value.startswith(("/", "\\"))
        or ".." in posix.parts
        or ".." in windows.parts
    ):
        raise ValueError(f"unsafe package-relative path: {value}")


def package_path(relative_path):
    reject_package_asset_path(relative_path)
    path = (ROOT / Path(relative_path)).resolve()
    root = ROOT.resolve()
    try:
        path.relative_to(root)
    except ValueError as error:
        raise ValueError(f"package path escapes package root: {relative_path}") from error
    return path


def f32(value):
    return struct.unpack("<f", struct.pack("<f", value))[0]


def f32_bits(value):
    return struct.pack("<f", value)


def f32_bits_u32(value):
    return struct.unpack("<I", f32_bits(value))[0]


def u32_to_f32(value):
    return struct.unpack("<f", struct.pack("<I", value))[0]


def f32_ulp_spacing(value):
    value = abs(f32(value))
    if value == 0.0:
        return u32_to_f32(1)
    bits = f32_bits_u32(value)
    if bits >= 0x7F800000:
        return math.inf
    return float(u32_to_f32(bits + 1)) - float(value)


def read_meshbin(relative_path):
    path = package_path(relative_path)
    size = path.stat().st_size
    if size < 24:
        raise ValueError(f"unsupported or truncated meshbin: {relative_path}")
    with path.open("rb") as handle:
        header = handle.read(24)
        if len(header) != 24 or header[:8] != b"SLMBIN01":
            raise ValueError(f"unsupported or truncated meshbin: {relative_path}")
        vertex_count, index_count = struct.unpack_from("<QQ", header, 8)
        if vertex_count == 0 or index_count % 3 != 0:
            raise ValueError(f"invalid counts in {relative_path}")
        expected = 24 + vertex_count * 12 + index_count * 4
        if size != expected:
            raise ValueError(f"{relative_path} has {size} bytes; expected {expected}")
        data = handle.read()
    offset = 0
    positions = []
    for _ in range(vertex_count):
        position = struct.unpack_from("<fff", data, offset)
        if not all(math.isfinite(component) for component in position):
            raise ValueError(f"non-finite position in {relative_path}")
        positions.append(position)
        offset += 12
    indices = []
    for index_offset in range(index_count):
        indices.append(struct.unpack_from("<I", data, offset + index_offset * 4)[0])
    if any(index >= vertex_count for index in indices):
        raise ValueError(f"out-of-range triangle index in {relative_path}")
    for offset in range(0, len(indices), 3):
        triangle = indices[offset : offset + 3]
        if len(set(triangle)) != 3:
            raise ValueError(f"triangle with repeated indices in {relative_path}")
    return positions, indices


def read_positions(relative_path, count):
    count = require_nonnegative_int(count, "position count")
    path = package_path(relative_path)
    size = path.stat().st_size
    expected = count * 12
    if size != expected:
        raise ValueError(f"{relative_path} has {size} bytes; expected {expected}")
    data = path.read_bytes()
    positions = [struct.unpack_from("<fff", data, index * 12) for index in range(count)]
    if not all(math.isfinite(component) for position in positions for component in position):
        raise ValueError(f"non-finite position in {relative_path}")
    return positions


def read_u32s(relative_path):
    path = package_path(relative_path)
    size = path.stat().st_size
    if size % 4 != 0:
        raise ValueError(f"{relative_path} byte length is not divisible by four")
    data = path.read_bytes()
    return [struct.unpack_from("<I", data, offset)[0] for offset in range(0, size, 4)]


def fnv1a_update(value, payload):
    for byte in payload:
        value ^= byte
        value = (value * FNV_PRIME) & 0xFFFFFFFFFFFFFFFF
    return value


def topology_hash(vertex_count, indices):
    value = FNV_OFFSET
    value = fnv1a_update(value, struct.pack("<Q", vertex_count))
    value = fnv1a_update(value, struct.pack("<Q", len(indices)))
    for index in indices:
        value = fnv1a_update(value, struct.pack("<I", index))
    return f"fnv1a64:{value:016x}"


def positions_bit_equal(left, right):
    return len(left) == len(right) and all(
        f32_bits(a) == f32_bits(b)
        for left_position, right_position in zip(left, right)
        for a, b in zip(left_position, right_position)
    )


def matrices_bit_equal(left, right):
    return len(left) == len(right) and all(
        f32_bits(actual) == f32_bits(expected)
        for actual, expected in zip(left, right)
    )


def apply_affine(positions, matrix):
    matrix = require_f32_list(matrix, 16, "affine matrix")
    result = []
    for x, y, z in positions:
        transformed = []
        for offset in (0, 4, 8):
            value = f32(matrix[offset] * x)
            value = f32(value + f32(matrix[offset + 1] * y))
            value = f32(value + f32(matrix[offset + 2] * z))
            value = f32(value + matrix[offset + 3])
            transformed.append(value)
        result.append(tuple(transformed))
    return result


def translation_matrix(translation):
    tx, ty, tz = translation
    return [
        1.0, 0.0, 0.0, tx,
        0.0, 1.0, 0.0, ty,
        0.0, 0.0, 1.0, tz,
        0.0, 0.0, 0.0, 1.0,
    ]


def rigid_matrix(rotation, translation):
    tx, ty, tz = translation
    return [
        rotation[0], rotation[1], rotation[2], tx,
        rotation[3], rotation[4], rotation[5], ty,
        rotation[6], rotation[7], rotation[8], tz,
        0.0, 0.0, 0.0, 1.0,
    ]


def similarity_matrix(rotation, scale, translation):
    tx, ty, tz = translation
    return [
        f32(scale * rotation[0]), f32(scale * rotation[1]), f32(scale * rotation[2]), tx,
        f32(scale * rotation[3]), f32(scale * rotation[4]), f32(scale * rotation[5]), ty,
        f32(scale * rotation[6]), f32(scale * rotation[7]), f32(scale * rotation[8]), tz,
        0.0, 0.0, 0.0, 1.0,
    ]


def dot(left, right):
    return sum(float(a) * float(b) for a, b in zip(left, right))


def cross(left, right):
    return (
        float(left[1]) * float(right[2]) - float(left[2]) * float(right[1]),
        float(left[2]) * float(right[0]) - float(left[0]) * float(right[2]),
        float(left[0]) * float(right[1]) - float(left[1]) * float(right[0]),
    )


def scale(vector, scalar):
    return tuple(f32(component * scalar) for component in vector)


def sub(left, right):
    return tuple(f32(a - b) for a, b in zip(left, right))


def add(left, right):
    return tuple(f32(a + b) for a, b in zip(left, right))


def normalize(vector):
    length = f32(math.sqrt(dot(vector, vector)))
    if length <= MIN_AXIS_LENGTH or not math.isfinite(length):
        return None
    return scale(vector, f32(1.0 / length))


def row_length(row):
    return math.sqrt(dot(row, row))


def determinant_3x3(matrix):
    a, b, c, d, e, f, g, h, i = (float(value) for value in matrix)
    return a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)


def is_proper_rotation(rotation):
    rows = [rotation[0:3], rotation[3:6], rotation[6:9]]
    unit_rows = all(
        abs(row_length(row) - 1.0) <= ROTATION_ORTHONORMAL_TOLERANCE for row in rows
    )
    orthogonal_rows = (
        abs(dot(rows[0], rows[1])) <= ROTATION_ORTHONORMAL_TOLERANCE
        and abs(dot(rows[0], rows[2])) <= ROTATION_ORTHONORMAL_TOLERANCE
        and abs(dot(rows[1], rows[2])) <= ROTATION_ORTHONORMAL_TOLERANCE
    )
    determinant = determinant_3x3(rotation)
    return (
        unit_rows
        and orthogonal_rows
        and math.isfinite(determinant)
        and abs(determinant - 1.0) <= ROTATION_ORTHONORMAL_TOLERANCE
    )


def reject_semantic_parameters(operator, keys, label):
    for key in keys:
        if operator.get(key) is not None:
            raise ValueError(f"{label} must not declare {key}")


def validate_affine_operator(operator):
    operator = require_mapping(operator, "affine operator")
    matrix = require_f32_list(
        operator.get("matrix_row_major_4x4"), 16, "affine matrix_row_major_4x4"
    )
    if any(
        f32_bits(actual) != f32_bits(expected)
        for actual, expected in zip(matrix[12:16], (0.0, 0.0, 0.0, 1.0))
    ):
        raise ValueError("affine matrix bottom row must be exactly [0, 0, 0, 1]")
    semantic_family = operator.get("semantic_family")
    if semantic_family == "general_affine":
        reject_semantic_parameters(
            operator,
            ("translation", "rotation_row_major_3x3", "uniform_scale"),
            "general affine",
        )
    elif semantic_family == "translation":
        translation = require_f32_list(operator.get("translation"), 3, "translation")
        reject_semantic_parameters(
            operator, ("rotation_row_major_3x3", "uniform_scale"), "translation"
        )
        if not matrices_bit_equal(matrix, translation_matrix(translation)):
            raise ValueError("translation matrix must match translation parameters")
    elif semantic_family == "rigid_transform":
        translation = require_f32_list(operator.get("translation"), 3, "rigid transform")
        rotation = require_f32_list(
            operator.get("rotation_row_major_3x3"), 9, "rigid transform rotation"
        )
        if operator.get("uniform_scale") is not None:
            raise ValueError("rigid transform must not declare uniform_scale")
        if not is_proper_rotation(rotation):
            raise ValueError("rigid transform rotation is not a proper basis")
        if not matrices_bit_equal(matrix, rigid_matrix(rotation, translation)):
            raise ValueError("rigid transform matrix must match semantic parameters")
    elif semantic_family == "similarity_transform":
        translation = require_f32_list(operator.get("translation"), 3, "similarity transform")
        rotation = require_f32_list(
            operator.get("rotation_row_major_3x3"), 9, "similarity transform rotation"
        )
        scale_value = require_finite_number(
            operator.get("uniform_scale"), "similarity transform uniform_scale"
        )
        scale_value = f32(scale_value)
        if scale_value <= 0.0:
            raise ValueError("similarity transform uniform_scale must be positive")
        if not is_proper_rotation(rotation):
            raise ValueError("similarity transform rotation is not a proper basis")
        if not matrices_bit_equal(matrix, similarity_matrix(rotation, scale_value, translation)):
            raise ValueError("similarity transform matrix must match semantic parameters")
    else:
        raise ValueError(f"unsupported affine semantic family: {semantic_family}")
    return matrix


def validate_bend_parameters(parameters):
    parameters = require_mapping(parameters, "bend parameters")
    origin = require_f32_list(parameters.get("origin"), 3, "bend origin")
    longitudinal_axis = require_f32_list(
        parameters.get("longitudinal_axis"), 3, "bend longitudinal_axis"
    )
    bend_direction = require_f32_list(
        parameters.get("bend_direction"), 3, "bend bend_direction"
    )
    angle_radians = f32(require_finite_number(parameters.get("angle_radians"), "bend angle"))
    interval_start = f32(
        require_finite_number(parameters.get("interval_start"), "bend interval_start")
    )
    interval_end = f32(
        require_finite_number(parameters.get("interval_end"), "bend interval_end")
    )
    if interval_end < interval_start:
        raise ValueError("bend interval_end must be greater than or equal to interval_start")

    axis = normalize(longitudinal_axis)
    if axis is None:
        raise ValueError("bend longitudinal_axis must be non-zero")
    direction_dot_axis = f32(dot(bend_direction, axis))
    projected_direction = sub(bend_direction, scale(axis, direction_dot_axis))
    direction = normalize(projected_direction)
    if direction is None:
        raise ValueError("bend_direction must have a component orthogonal to the axis")
    binormal = normalize(cross(axis, direction))
    if binormal is None:
        raise ValueError("bend frame is degenerate")
    return {
        "origin": tuple(origin),
        "longitudinal_axis": tuple(axis),
        "bend_direction": tuple(direction),
        "binormal": tuple(binormal),
        "angle_radians": angle_radians,
        "interval_start": interval_start,
        "interval_end": interval_end,
    }


def evaluate_bend(parameters, positions):
    bend = validate_bend_parameters(parameters)
    angle = bend["angle_radians"]
    if abs(angle) <= IDENTITY_ANGLE_EPSILON:
        return list(positions)
    interval_start = bend["interval_start"]
    interval_end = bend["interval_end"]
    interval_length = f32(interval_end - interval_start)
    if interval_length <= 0.0:
        raise ValueError("non-identity bends require a positive interval length")
    radius = f32(interval_length / angle)
    origin = bend["origin"]
    axis = bend["longitudinal_axis"]
    direction = bend["bend_direction"]
    binormal = bend["binormal"]
    result = []
    for position in positions:
        relative = sub(position, origin)
        local_x = f32(dot(relative, direction))
        local_y = f32(dot(relative, axis))
        local_z = f32(dot(relative, binormal))
        if local_y < interval_start:
            result.append(tuple(position))
            continue
        if local_y <= interval_end:
            theta = f32(angle * f32((local_y - interval_start) / interval_length))
            sin_theta = f32(math.sin(theta))
            cos_theta = f32(math.cos(theta))
            bent_x = f32(f32(radius * f32(1.0 - cos_theta)) + f32(local_x * cos_theta))
            bent_y = f32(
                interval_start
                + f32(radius * sin_theta)
                - f32(local_x * sin_theta)
            )
        else:
            sin_angle = f32(math.sin(angle))
            cos_angle = f32(math.cos(angle))
            bent_x = f32(
                f32(radius * f32(1.0 - cos_angle))
                + f32(local_x * cos_angle)
                + f32(f32(local_y - interval_end) * sin_angle)
            )
            bent_y = f32(
                interval_start
                + f32(radius * sin_angle)
                - f32(local_x * sin_angle)
                + f32(f32(local_y - interval_end) * cos_angle)
            )
        world = add(
            origin,
            add(
                add(scale(direction, bent_x), scale(axis, bent_y)),
                scale(binormal, local_z),
            ),
        )
        result.append(tuple(f32(component) for component in world))
    return result


def comparison_report(evaluated, baked, policy):
    if len(evaluated) != len(baked):
        raise ValueError("semantic evaluation vertex count does not match baked stage")
    mode = policy["mode"]
    absolute_epsilon = float(policy["absolute_epsilon"])
    relative_epsilon = float(policy["relative_epsilon"])
    ulp_multiplier = float(policy["ulp_multiplier"])
    max_component_error = 0.0
    max_euclidean_error = 0.0
    total_euclidean_error = 0.0
    total_squared_euclidean_error = 0.0
    outside_tolerance = 0
    bit_exact = positions_bit_equal(evaluated, baked)
    for left, right in zip(evaluated, baked):
        component_errors = [abs(float(a) - float(b)) for a, b in zip(left, right)]
        euclidean = math.sqrt(sum(error * error for error in component_errors))
        max_component_error = max(max_component_error, max(component_errors))
        max_euclidean_error = max(max_euclidean_error, euclidean)
        total_euclidean_error += euclidean
        total_squared_euclidean_error += euclidean * euclidean
        if mode == "bit_exact":
            outside = any(f32_bits(a) != f32_bits(b) for a, b in zip(left, right))
        else:
            outside = False
            for a, b, error in zip(left, right, component_errors):
                local = max(abs(float(a)), abs(float(b)))
                allowed = (
                    absolute_epsilon
                    + relative_epsilon * local
                    + ulp_multiplier * f32_ulp_spacing(local)
                )
                if error > allowed:
                    outside = True
                    break
        if outside:
            outside_tolerance += 1
    count = max(len(evaluated), 1)
    passed = bit_exact if mode == "bit_exact" else outside_tolerance == 0
    return {
        "max_component_error": max_component_error,
        "max_euclidean_error": max_euclidean_error,
        "mean_euclidean_error": total_euclidean_error / count,
        "rms_euclidean_error": math.sqrt(total_squared_euclidean_error / count),
        "outside_tolerance": outside_tolerance,
        "positions_bit_exact": bit_exact,
        "passed": passed,
    }


def validate_semantic_policy(policy, label):
    policy = require_mapping(policy, label)
    mode = policy.get("mode")
    if mode not in ("bit_exact", "tolerance"):
        raise ValueError(f"{label} has unsupported mode: {mode}")
    for field in ("absolute_epsilon", "relative_epsilon", "ulp_multiplier"):
        value = require_finite_number(policy.get(field), f"{label}.{field}")
        if value < 0.0:
            raise ValueError(f"{label}.{field} must be non-negative")
    return policy


def validate_semantic_report(report, label):
    report = require_mapping(report, label)
    for field in (
        "max_component_error",
        "max_euclidean_error",
        "mean_euclidean_error",
        "rms_euclidean_error",
    ):
        value = require_finite_number(report.get(field), f"{label}.{field}")
        if value < 0.0:
            raise ValueError(f"{label}.{field} must be non-negative")
    require_nonnegative_int(report.get("outside_tolerance"), f"{label}.outside_tolerance")
    require_bool(report.get("passed"), f"{label}.passed")
    return report


def validate_stage(stage, expected_index):
    stage = require_mapping(stage, f"operator {expected_index} stage")
    actual_index = require_nonnegative_int(stage.get("stage_index"), "stage_index")
    if actual_index != expected_index:
        raise ValueError(
            f"stage index {actual_index} does not match expected index {expected_index}"
        )
    operator_id = require_string(stage.get("operator_id"), "operator_id")
    label = require_string(stage.get("label"), "stage label")
    baked_positions_file = require_string(
        stage.get("baked_positions_file"), "baked_positions_file"
    )
    reject_package_asset_path(baked_positions_file)
    validate_semantic_policy(
        stage.get("semantic_verification_policy"),
        "semantic_verification_policy",
    )
    validate_semantic_report(
        stage.get("semantic_verification_report"),
        "semantic_verification_report",
    )
    return operator_id, label


def validate_manifest_schema(manifest):
    manifest = require_mapping(manifest, "manifest")
    if manifest.get("schema_version") != SUPPORTED_SCHEMA_VERSION:
        raise ValueError(
            f"unsupported schema version {manifest.get('schema_version')}; "
            f"expected {SUPPORTED_SCHEMA_VERSION}"
        )
    if manifest.get("coordinate_system") != "right-handed-y-up":
        raise ValueError("unsupported coordinate system; expected right-handed-y-up")
    if manifest.get("numeric_format") != {
        "scalar": "float32",
        "endian": "little",
        "affine_evaluation": "float32_stepwise_no_fma",
    }:
        raise ValueError(
            "unsupported numeric format; expected little-endian float32 with "
            "stepwise non-fused affine arithmetic"
        )

    for asset_name in ("source", "target"):
        asset = require_mapping(manifest.get(asset_name), asset_name)
        reject_package_asset_path(require_string(asset.get("path"), f"{asset_name}.path"))
        require_nonnegative_int(asset.get("vertex_count"), f"{asset_name}.vertex_count")
        require_nonnegative_int(asset.get("triangle_count"), f"{asset_name}.triangle_count")

    topology = require_mapping(manifest.get("topology"), "topology")
    require_nonnegative_int(topology.get("vertex_count"), "topology.vertex_count")
    require_nonnegative_int(topology.get("triangle_count"), "topology.triangle_count")
    require_nonnegative_int(topology.get("index_count"), "topology.index_count")
    require_string(topology.get("hash"), "topology.hash")

    operators = manifest.get("operators")
    if not isinstance(operators, list) or len(operators) == 0:
        raise ValueError("schema-3 packages must contain at least a lossless correction")

    operator_ids = set()
    labels = {"Basis"}
    lossless_count = 0
    for operator_index, operator in enumerate(operators):
        operator = require_mapping(operator, f"operator {operator_index}")
        operator_id, label = validate_stage(operator.get("stage"), operator_index)
        if operator_id in operator_ids:
            raise ValueError(f"duplicate operator ID: {operator_id}")
        if label in labels:
            raise ValueError(f"duplicate or reserved shape-key label: {label}")
        operator_ids.add(operator_id)
        labels.add(label)

        kind = operator.get("kind")
        if kind == "affine":
            validate_affine_operator(operator.get("operator"))
        elif kind == "bend":
            validate_bend_parameters(operator.get("parameters"))
        elif kind == "lossless_correction":
            lossless_count += 1
            if operator_index + 1 != len(operators) or lossless_count > 1:
                raise ValueError("lossless correction must be the final operator")
            correction = require_mapping(operator.get("correction"), "lossless correction")
            reject_package_asset_path(
                require_string(correction.get("residual_index_file"), "residual_index_file")
            )
            reject_package_asset_path(
                require_string(
                    correction.get("residual_position_file"), "residual_position_file"
                )
            )
            require_nonnegative_int(
                correction.get("corrected_vertex_count"), "corrected_vertex_count"
            )
        else:
            raise ValueError(f"unsupported operator kind: {kind}")
    if lossless_count != 1:
        raise ValueError("schema-3 packages must end with exactly one lossless correction")
    return manifest


def apply_lossless_correction(operator, current):
    correction = operator["correction"]
    indices = read_u32s(correction["residual_index_file"])
    positions = read_positions(correction["residual_position_file"], len(indices))
    corrected_vertex_count = require_nonnegative_int(
        correction.get("corrected_vertex_count"), "corrected_vertex_count"
    )
    if len(indices) != corrected_vertex_count:
        raise ValueError("lossless correction count does not match its payload")
    if any(index >= len(current) for index in indices):
        raise ValueError("lossless correction contains an out-of-range vertex index")
    if any(left >= right for left, right in zip(indices, indices[1:])):
        raise ValueError("lossless correction indices must be unique and increasing")
    corrected = list(current)
    for vertex_index, position in zip(indices, positions):
        corrected[vertex_index] = position
    return corrected


def replay_operators(manifest, source_positions):
    current = list(source_positions)
    stages = []
    for operator_index, operator in enumerate(manifest["operators"]):
        stage = operator["stage"]
        baked = read_positions(stage["baked_positions_file"], len(source_positions))
        kind = operator.get("kind")
        if kind == "affine":
            matrix = validate_affine_operator(operator.get("operator"))
            evaluated = apply_affine(current, matrix)
            report = comparison_report(
                evaluated,
                baked,
                {"mode": "bit_exact", "absolute_epsilon": 0.0, "relative_epsilon": 0.0, "ulp_multiplier": 0.0},
            )
            if not report["passed"]:
                raise ValueError("affine semantic evaluation is not bit-exact with its baked stage")
        elif kind == "bend":
            evaluated = evaluate_bend(operator.get("parameters"), current)
            report = comparison_report(
                evaluated, baked, stage["semantic_verification_policy"]
            )
            if not report["passed"]:
                raise ValueError("bend semantic evaluation does not satisfy its baked-stage policy")
        elif kind == "lossless_correction":
            evaluated = apply_lossless_correction(operator, current)
            report = comparison_report(
                evaluated,
                baked,
                {"mode": "bit_exact", "absolute_epsilon": 0.0, "relative_epsilon": 0.0, "ulp_multiplier": 0.0},
            )
            if not report["passed"]:
                raise ValueError("lossless correction is not bit-exact with its baked stage")
        else:
            raise ValueError(f"unsupported operator kind: {kind}")
        current = baked
        stages.append(
            {
                "index": operator_index,
                "kind": kind,
                "operator_id": stage["operator_id"],
                "label": stage["label"],
                "positions": baked,
                "semantic_report": report,
            }
        )
    return current, stages


def faces_from_indices(indices):
    return [tuple(indices[index : index + 3]) for index in range(0, len(indices), 3)]


def remove_object(name):
    obj = bpy.data.objects.get(name)
    if obj is not None:
        bpy.data.objects.remove(obj, do_unlink=True)


def add_vertex_ids(mesh):
    attribute = mesh.attributes.get(VERTEX_ID_ATTRIBUTE)
    if attribute is None:
        attribute = mesh.attributes.new(name=VERTEX_ID_ATTRIBUTE, type="INT", domain="POINT")
    if len(attribute.data) != len(mesh.vertices):
        raise RuntimeError("vertex ID attribute has the wrong size")
    for index, value in enumerate(attribute.data):
        value.value = index


def create_mesh_object(name, positions, indices):
    mesh = bpy.data.meshes.new(f"{name}_Mesh")
    mesh.from_pydata(positions, [], faces_from_indices(indices))
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    add_vertex_ids(mesh)
    return obj


def set_shape_key_positions(key, positions):
    if len(key.data) != len(positions):
        raise ValueError("shape key vertex count does not match position payload")
    for vertex, position in zip(key.data, positions):
        vertex.co = position


def mesh_arrays(mesh):
    positions = [tuple(f32(component) for component in vertex.co) for vertex in mesh.vertices]
    indices = []
    for polygon in mesh.polygons:
        vertices = tuple(polygon.vertices)
        if len(vertices) != 3:
            raise ValueError("reconstructed Blender mesh contains a non-triangular face")
        indices.extend(vertices)
    return positions, indices


def vertex_ids_exact(mesh):
    attribute = mesh.attributes.get(VERTEX_ID_ATTRIBUTE)
    return attribute is not None and len(attribute.data) == len(mesh.vertices) and all(
        value.value == index for index, value in enumerate(attribute.data)
    )


def verification_metrics(positions, target_positions, indices, target_indices):
    topology_exact = len(positions) == len(target_positions) and indices == target_indices
    max_component_error = 0.0
    max_euclidean_error = 0.0
    total_euclidean_error = 0.0
    total_squared_euclidean_error = 0.0
    outside_tolerance = 0
    positions_bit_exact = positions_bit_equal(positions, target_positions)
    if len(positions) == len(target_positions):
        for left, right in zip(positions, target_positions):
            differences = [abs(float(a) - float(b)) for a, b in zip(left, right)]
            euclidean = math.sqrt(sum(value * value for value in differences))
            max_component_error = max(max_component_error, max(differences))
            max_euclidean_error = max(max_euclidean_error, euclidean)
            total_euclidean_error += euclidean
            total_squared_euclidean_error += euclidean * euclidean
            if euclidean > 0.0:
                outside_tolerance += 1
    count = max(len(positions), 1)
    return {
        "topology_exact": topology_exact,
        "positions_bit_exact": positions_bit_exact,
        "vertex_count": len(positions),
        "triangle_count": len(indices) // 3,
        "max_component_error": max_component_error,
        "max_euclidean_error": max_euclidean_error,
        "mean_euclidean_error": total_euclidean_error / count,
        "rms_euclidean_error": math.sqrt(total_squared_euclidean_error / count),
        "outside_tolerance": outside_tolerance,
    }


def build_package_report(manifest, source_positions, source_indices, target_positions, target_indices, stages):
    final_positions = stages[-1]["positions"] if stages else []
    metrics = verification_metrics(final_positions, target_positions, source_indices, target_indices)
    topology_fingerprint = topology_hash(len(source_positions), source_indices)
    residual_count = manifest["operators"][-1]["correction"]["corrected_vertex_count"]
    return {
        "schema_version": SUPPORTED_SCHEMA_VERSION,
        "topology_exact": source_indices == target_indices and len(source_positions) == len(target_positions),
        "topology_hash_matches_manifest": topology_fingerprint == manifest["topology"]["hash"],
        "positions_bit_exact": metrics["positions_bit_exact"],
        "vertex_count": len(source_positions),
        "triangle_count": len(source_indices) // 3,
        "operator_count": len(manifest["operators"]),
        "stage_count": len(stages),
        "residual_vertex_count": residual_count,
        "max_component_error": metrics["max_component_error"],
        "max_euclidean_error": metrics["max_euclidean_error"],
        "outside_tolerance": metrics["outside_tolerance"],
        "semantic_stage_reports_passed": all(
            stage["semantic_report"]["passed"] for stage in stages
        ),
    }


def validate_package_report(manifest, package_report):
    expected = manifest.get("package_verification")
    if expected is None:
        return True
    for field, actual_value in package_report.items():
        if field not in expected:
            raise ValueError(f"package_verification is missing {field}")
        expected_value = expected[field]
        if isinstance(actual_value, float):
            if not math.isfinite(expected_value) or abs(float(expected_value) - actual_value) > 1.0e-12:
                raise ValueError(f"package_verification field {field} does not match replay")
        elif expected_value != actual_value:
            raise ValueError(f"package_verification field {field} does not match replay")
    return True


def load_and_validate_package(manifest_file):
    manifest = json.loads(package_path(manifest_file).read_text(encoding="utf-8"))
    validate_manifest_schema(manifest)

    source_positions, source_indices = read_meshbin(manifest["source"]["path"])
    target_positions, target_indices = read_meshbin(manifest["target"]["path"])
    if source_indices != target_indices or len(source_positions) != len(target_positions):
        raise ValueError("source and target meshbin topology differs")
    expected_hash = topology_hash(len(source_positions), source_indices)
    if expected_hash != manifest["topology"]["hash"]:
        raise ValueError("manifest topology fingerprint does not match package payload")

    if manifest["source"]["vertex_count"] != len(source_positions):
        raise ValueError("source vertex count does not match manifest")
    if manifest["source"]["triangle_count"] != len(source_indices) // 3:
        raise ValueError("source triangle count does not match manifest")
    if manifest["target"]["vertex_count"] != len(target_positions):
        raise ValueError("target vertex count does not match manifest")
    if manifest["target"]["triangle_count"] != len(target_indices) // 3:
        raise ValueError("target triangle count does not match manifest")

    topology = manifest["topology"]
    if (
        topology["vertex_count"] != len(source_positions)
        or topology["triangle_count"] != len(source_indices) // 3
        or topology["index_count"] != len(source_indices)
    ):
        raise ValueError("topology counts do not match source meshbin")

    final_positions, stages = replay_operators(manifest, source_positions)
    if not positions_bit_equal(final_positions, target_positions):
        raise ValueError("schema-3 baked stages do not reconstruct target positions exactly")
    package_report = build_package_report(
        manifest, source_positions, source_indices, target_positions, target_indices, stages
    )
    validate_package_report(manifest, package_report)
    return (
        manifest,
        source_positions,
        source_indices,
        target_positions,
        target_indices,
        stages,
        package_report,
    )


def stage_reports_for_json(stages):
    return [
        {
            "index": stage["index"],
            "kind": stage["kind"],
            "operator_id": stage["operator_id"],
            "label": stage["label"],
            "semantic_report": stage["semantic_report"],
        }
        for stage in stages
    ]


def object_common_properties(obj, manifest):
    obj["shape_lab_topology_hash"] = manifest["topology"]["hash"]
    obj["shape_lab_schema_version"] = manifest["schema_version"]
    obj["shape_lab_coordinate_system"] = manifest["coordinate_system"]


def report_for_object(obj, manifest, target_positions, target_indices, mode):
    positions, indices = mesh_arrays(obj.data)
    metrics = verification_metrics(positions, target_positions, indices, target_indices)
    topology_fingerprint = topology_hash(len(positions), indices)
    metrics.update(
        {
            "mode": mode,
            "blender_version": bpy.app.version_string,
            "object_name": obj.name,
            "topology_hash": topology_fingerprint,
            "topology_hash_matches_manifest": topology_fingerprint
            == manifest["topology"]["hash"],
            "vertex_ids_exact": vertex_ids_exact(obj.data),
            "object_topology_property_matches": obj.get("shape_lab_topology_hash")
            == manifest["topology"]["hash"],
            "object_schema_property_matches": obj.get("shape_lab_schema_version")
            == manifest["schema_version"],
            "object_coordinate_property_matches": obj.get("shape_lab_coordinate_system")
            == manifest["coordinate_system"],
        }
    )
    metrics["verification_passed"] = all(
        [
            metrics["topology_exact"],
            metrics["positions_bit_exact"],
            metrics["topology_hash_matches_manifest"],
            metrics["vertex_ids_exact"],
            metrics["object_topology_property_matches"],
            metrics["object_schema_property_matches"],
            metrics["object_coordinate_property_matches"],
            metrics["outside_tolerance"] == 0,
        ]
    )
    return metrics


def report_for_editable_object(
    obj,
    manifest,
    source_positions,
    target_positions,
    target_indices,
    stages,
    mode,
):
    basis_positions, indices = mesh_arrays(obj.data)
    shape_keys = obj.data.shape_keys
    expected_shape_key_count = len(stages) + 1
    if shape_keys is None:
        raise ValueError("editable reconstruction is missing cumulative shape keys")

    key_blocks = list(shape_keys.key_blocks)
    expected_names = ["Basis"] + [stage["label"] for stage in stages]
    actual_names = [key.name for key in key_blocks]
    shape_key_count_exact = len(key_blocks) == expected_shape_key_count
    shape_key_names_exact = actual_names == expected_names
    basis_mesh_positions_exact = positions_bit_equal(basis_positions, source_positions)

    stage_results = []
    stage_positions_exact = shape_key_count_exact
    if shape_key_count_exact:
        expected_payloads = [source_positions] + [stage["positions"] for stage in stages]
        for index, (key, expected_name, expected_positions) in enumerate(
            zip(key_blocks, expected_names, expected_payloads)
        ):
            actual_positions = [
                tuple(f32(component) for component in point.co) for point in key.data
            ]
            positions_exact = positions_bit_equal(actual_positions, expected_positions)
            stage_positions_exact = stage_positions_exact and positions_exact
            stage_results.append(
                {
                    "index": index,
                    "expected_name": expected_name,
                    "actual_name": key.name,
                    "positions_bit_exact": positions_exact,
                    "value": float(key.value),
                }
            )
    else:
        stage_positions_exact = False

    final_key = key_blocks[-1] if key_blocks else None
    final_positions = (
        [tuple(f32(component) for component in point.co) for point in final_key.data]
        if final_key is not None
        else []
    )
    metrics = verification_metrics(
        final_positions, target_positions, indices, target_indices
    )
    topology_fingerprint = topology_hash(len(final_positions), indices)
    preceding_shape_key_values_zero = all(
        abs(float(key.value)) <= 1.0e-7 for key in key_blocks[1:-1]
    )
    final_shape_key_value = float(final_key.value) if final_key is not None else 0.0
    metrics.update(
        {
            "mode": mode,
            "blender_version": bpy.app.version_string,
            "object_name": obj.name,
            "topology_hash": topology_fingerprint,
            "topology_hash_matches_manifest": topology_fingerprint
            == manifest["topology"]["hash"],
            "vertex_ids_exact": vertex_ids_exact(obj.data),
            "object_topology_property_matches": obj.get("shape_lab_topology_hash")
            == manifest["topology"]["hash"],
            "object_schema_property_matches": obj.get("shape_lab_schema_version")
            == manifest["schema_version"],
            "object_coordinate_property_matches": obj.get("shape_lab_coordinate_system")
            == manifest["coordinate_system"],
            "shape_key_count": len(key_blocks),
            "expected_shape_key_count": expected_shape_key_count,
            "shape_key_count_exact": shape_key_count_exact,
            "shape_key_names": actual_names,
            "expected_shape_key_names": expected_names,
            "shape_key_names_exact": shape_key_names_exact,
            "basis_mesh_positions_exact": basis_mesh_positions_exact,
            "stage_positions_exact": stage_positions_exact,
            "stage_results": stage_results,
            "preceding_shape_key_values_zero": preceding_shape_key_values_zero,
            "final_shape_key_name": final_key.name if final_key is not None else None,
            "final_shape_key_value": final_shape_key_value,
        }
    )
    metrics["verification_passed"] = all(
        [
            metrics["topology_exact"],
            metrics["positions_bit_exact"],
            metrics["topology_hash_matches_manifest"],
            metrics["vertex_ids_exact"],
            metrics["object_topology_property_matches"],
            metrics["object_schema_property_matches"],
            metrics["object_coordinate_property_matches"],
            metrics["outside_tolerance"] == 0,
            metrics["shape_key_count_exact"],
            metrics["shape_key_names_exact"],
            metrics["basis_mesh_positions_exact"],
            metrics["stage_positions_exact"],
            metrics["preceding_shape_key_values_zero"],
            abs(metrics["final_shape_key_value"] - 1.0) <= 1.0e-7,
        ]
    )
    return metrics


def write_report(path, report):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def reconstruct(manifest, source_positions, source_indices, target_positions, stages):
    remove_object(SOURCE_OBJECT_NAME)
    remove_object(BAKED_OBJECT_NAME)

    editable = create_mesh_object(SOURCE_OBJECT_NAME, source_positions, source_indices)
    bpy.context.view_layer.objects.active = editable
    editable.select_set(True)
    editable.shape_key_add(name="Basis")
    final_key = None
    for stage in stages:
        key = editable.shape_key_add(name=stage["label"])
        set_shape_key_positions(key, stage["positions"])
        key.value = 0.0
        final_key = key
    if final_key is None:
        raise RuntimeError("operator replay produced no inspectable stages")
    final_key.value = 1.0
    editable.active_shape_key_index = len(editable.data.shape_keys.key_blocks) - 1
    object_common_properties(editable, manifest)

    reconstructed_positions = stages[-1]["positions"]
    baked = create_mesh_object(BAKED_OBJECT_NAME, reconstructed_positions, source_indices)
    object_common_properties(baked, manifest)

    final_key_positions = [
        tuple(f32(component) for component in point.co) for point in final_key.data
    ]
    if not positions_bit_equal(final_key_positions, target_positions):
        raise RuntimeError("final editable shape key is not bit-exact with target positions")
    return editable, baked


def execute(args):
    (
        manifest,
        source_positions,
        source_indices,
        target_positions,
        target_indices,
        stages,
        package_report,
    ) = load_and_validate_package(args.manifest)

    if args.verify_existing:
        baked = bpy.data.objects.get(BAKED_OBJECT_NAME)
        editable = bpy.data.objects.get(SOURCE_OBJECT_NAME)
        if baked is None:
            raise RuntimeError(f"{BAKED_OBJECT_NAME} was not found in the opened .blend file")
        if editable is None:
            raise RuntimeError(f"{SOURCE_OBJECT_NAME} was not found in the opened .blend file")
        report = report_for_object(
            baked, manifest, target_positions, target_indices, "verify_existing_saved_blend"
        )
        editable_report = report_for_editable_object(
            editable,
            manifest,
            source_positions,
            target_positions,
            target_indices,
            stages,
            "verify_existing_saved_blend_shape_key",
        )
    else:
        editable, baked = reconstruct(
            manifest,
            source_positions,
            source_indices,
            target_positions,
            stages,
        )
        report = report_for_object(
            baked, manifest, target_positions, target_indices, "reconstruct_in_memory"
        )
        editable_report = report_for_editable_object(
            editable,
            manifest,
            source_positions,
            target_positions,
            target_indices,
            stages,
            "reconstruct_in_memory_shape_key",
        )
        if not args.no_save:
            blend_path = output_path(args.output_blend)
            blend_path.parent.mkdir(parents=True, exist_ok=True)
            bpy.ops.wm.save_as_mainfile(filepath=str(blend_path))
            report["saved_blend"] = str(blend_path)

    report["editable_shape_key"] = editable_report
    report["package_replay"] = package_report
    report["stage_semantic_reports"] = stage_reports_for_json(stages)
    report["verification_passed"] = bool(
        report["verification_passed"]
        and editable_report["verification_passed"]
        and package_report["positions_bit_exact"]
        and package_report["topology_exact"]
        and package_report["topology_hash_matches_manifest"]
        and package_report["semantic_stage_reports_passed"]
    )
    return report


def main():
    args = command_line_arguments()
    report_path = output_path(args.report)
    try:
        report = execute(args)
        write_report(report_path, report)
        print(json.dumps(report, indent=2, sort_keys=True))
        if not report["verification_passed"]:
            raise RuntimeError(f"Shape Lab Blender verification failed; see {report_path}")
    except Exception as error:
        failure = {
            "schema_version": SUPPORTED_SCHEMA_VERSION,
            "mode": "verify_existing_saved_blend" if args.verify_existing else "reconstruct_in_memory",
            "verification_passed": False,
            "error": str(error),
        }
        try:
            write_report(report_path, failure)
        except Exception:
            pass
        print(json.dumps(failure, indent=2, sort_keys=True), file=sys.stderr)
        raise


if __name__ == "__main__":
    main()
"####;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn script_documents_schema_three_exact_replay() {
        let script = blender_reconstruction_script_v3(&BlenderAdapterOptions::default());

        assert!(script.contains("SUPPORTED_SCHEMA_VERSION = 3"));
        assert!(
            script.contains("for operator_index, operator in enumerate(manifest[\"operators\"]):")
        );
        assert!(script.contains("set_shape_key_positions(key, stage[\"positions\"])"));
        assert!(script.contains("ShapeLab_V3_Reconstructed_Baked"));
        assert!(!script.contains("Simple Deform"));
        assert!(!script.contains("SimpleDeform"));
    }

    #[test]
    fn options_are_embedded_as_python_literals() {
        let script = blender_reconstruction_script_v3(&BlenderAdapterOptions {
            manifest_file: "nested/manifest.json".to_owned(),
            report_file: "reports/out.json".to_owned(),
            verify_existing: true,
        });

        assert!(script.contains("MANIFEST_FILE = \"nested/manifest.json\""));
        assert!(script.contains("REPORT_FILE = \"reports/out.json\""));
        assert!(script.contains("DEFAULT_VERIFY_EXISTING = True"));
    }
}
