//! Background job contracts for explicit asset authoring.

#![allow(dead_code)]

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::PathBuf;
use std::sync::OnceLock;

use rayon::prelude::*;
use shape_asset::{
    AssetEdit, AssetEditProgram, AssetRecipe, ModelingOperationSpec, ParameterId, PartDefinitionId,
    PartInstanceId, RevisionId, descendants_of, instances_of_definition, validate_asset_recipe,
};
use shape_compile::export::{
    GroupedObjReport, ModelExportPackagePaths, recipe_hash, write_grouped_obj_export,
    write_model_package,
};
use shape_compile::validation::{
    ModelValidationReport, validate_model, validation_config_from_recipe,
};
use shape_compile::{
    AssetArtifact, ConstructionTimelineReport, build_construction_timeline_report, compile_asset,
};
use shape_core::Aabb;
use shape_mesh::TriangleMesh;
use shape_render::{
    MeshVisualDescriptor, OrbitCamera, RenderSettings, RenderedImage, fit_camera_to_bounds,
    render_mesh, visual_descriptor_for_mesh,
};
use shape_search::asset::scoring::{
    AssetCandidateInput, AssetScoredCandidate, AssetSelectionPolicy,
    score_and_select_asset_candidates_with_policy,
};
use shape_search::asset::{
    AssetCandidate as SearchAssetCandidate, AssetCandidateEditKind, AssetCandidateMode,
    AssetCandidateRequest, AssetChangeDiagnostic, generate_asset_candidates,
};

const DEFAULT_GENERATED_CANDIDATES: usize = 6;
const MIN_REFINE_PROPOSALS: usize = 48;
const MIN_EXPLORE_PROPOSALS: usize = 72;
const PROPOSAL_MULTIPLIER: usize = 12;
const ASSET_CANDIDATE_TRIANGLE_BUDGET: usize = 80_000;
const MAX_PROPOSAL_COMPILE_THREADS: usize = 4;

/// Monotonic app job identifier.
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) struct AssetJobId(pub u64);

/// Monotonic candidate generation identifier.
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) struct AssetGenerationId(pub u64);

/// Stable candidate identifier within the app state.
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) struct AssetCandidateId(pub u64);

/// Active-job buckets used by reducers to reject stale results by kind.
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum AssetJobSlot {
    CompileCurrentAsset,
    RenderCurrentPreview,
    GenerateCandidates,
    CompileCandidatePreviews,
    ExportObj,
    ExportPackage,
}

/// Candidate generation mode.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub(crate) enum AssetGenerationMode {
    Refine,
    Explore,
}

/// Requested output policy for a background job.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub(crate) enum AssetOutputPolicy {
    PreviewOnly,
    PackageExport,
    PreviewAndPackage,
}

/// Optional validation budgets carried with deterministic job requests.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub(crate) struct AssetValidationLimits {
    pub max_issues: usize,
}

/// Candidate recipe snapshot generated off the UI thread.
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct AssetCandidate {
    pub id: AssetCandidateId,
    pub slot: usize,
    pub label: String,
    pub recipe: AssetRecipe,
    pub changed_parameters: BTreeSet<ParameterId>,
    pub changes: Vec<AssetCandidateChange>,
    pub quality_penalty: f32,
    pub artifact: Option<AssetArtifact>,
}

/// Human-facing semantic edit summary generated by the asset search engine.
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct AssetCandidateChange {
    pub kind: AssetCandidateEditKind,
    pub subject: String,
    pub label: String,
    pub before: Option<String>,
    pub after: Option<String>,
    pub structural: bool,
}

struct CompiledSearchCandidate {
    input: AssetCandidateInput,
    candidate: Option<SearchAssetCandidate>,
    artifact: Option<AssetArtifact>,
}

/// Compact validation summary suitable for candidate grids.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct AssetValidationSummary {
    pub valid: bool,
    pub issue_count: usize,
}

/// Lightweight preview and topology summary for a candidate.
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct AssetCandidatePreview {
    pub candidate_id: AssetCandidateId,
    pub recipe_revision: RevisionId,
    pub thumbnail_rgba: Vec<u8>,
    pub thumbnail_width: u32,
    pub thumbnail_height: u32,
    pub camera: OrbitCamera,
    pub part_count: u64,
    pub triangle_count: u64,
    pub region_count: u64,
    pub validation_summary: AssetValidationSummary,
    pub changed_parameters: BTreeSet<ParameterId>,
    pub construction_timeline_summary: Vec<String>,
}

/// Per-candidate preview failure that does not fail the whole batch.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct AssetCandidatePreviewFailure {
    pub candidate_id: AssetCandidateId,
    pub message: String,
}

/// Current asset render preview.
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct AssetPreview {
    pub recipe_revision: RevisionId,
    pub mesh: TriangleMesh,
    pub image: RenderedImage,
    pub camera: OrbitCamera,
}

/// Full compile output plus timeline for the current recipe.
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct AssetCompileOutput {
    pub recipe_revision: RevisionId,
    pub artifact: AssetArtifact,
    pub model_validation: ModelValidationReport,
    pub timeline: ConstructionTimelineReport,
}

/// Deterministic background work request.
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct AssetJobRequest {
    pub job_id: AssetJobId,
    pub recipe_revision: RevisionId,
    pub kind: AssetJobKind,
    pub recipe: AssetRecipe,
    pub validation_limits: Option<AssetValidationLimits>,
    pub output_policy: AssetOutputPolicy,
}

impl AssetJobRequest {
    pub(crate) fn slot(&self) -> AssetJobSlot {
        self.kind.slot()
    }

    pub(crate) fn generation_id(&self) -> Option<AssetGenerationId> {
        self.kind.generation_id()
    }
}

/// Job kind-specific payloads.
#[derive(Debug, Clone, PartialEq)]
pub(crate) enum AssetJobKind {
    CompileCurrentAsset,
    RenderCurrentPreview {
        artifact: Option<Box<AssetArtifact>>,
        camera: Option<OrbitCamera>,
        render_settings: RenderSettings,
    },
    GenerateCandidates {
        generation_id: AssetGenerationId,
        mode: AssetGenerationMode,
        max_candidates: usize,
    },
    CompileCandidatePreviews {
        generation_id: AssetGenerationId,
        candidates: Vec<AssetCandidate>,
        camera: OrbitCamera,
        render_settings: RenderSettings,
    },
    ExportPackage {
        path: PathBuf,
    },
    ExportObj {
        path: PathBuf,
    },
}

impl AssetJobKind {
    pub(crate) fn slot(&self) -> AssetJobSlot {
        match self {
            Self::CompileCurrentAsset => AssetJobSlot::CompileCurrentAsset,
            Self::RenderCurrentPreview { .. } => AssetJobSlot::RenderCurrentPreview,
            Self::GenerateCandidates { .. } => AssetJobSlot::GenerateCandidates,
            Self::CompileCandidatePreviews { .. } => AssetJobSlot::CompileCandidatePreviews,
            Self::ExportObj { .. } => AssetJobSlot::ExportObj,
            Self::ExportPackage { .. } => AssetJobSlot::ExportPackage,
        }
    }

    pub(crate) fn generation_id(&self) -> Option<AssetGenerationId> {
        match self {
            Self::GenerateCandidates { generation_id, .. }
            | Self::CompileCandidatePreviews { generation_id, .. } => Some(*generation_id),
            Self::CompileCurrentAsset
            | Self::RenderCurrentPreview { .. }
            | Self::ExportObj { .. }
            | Self::ExportPackage { .. } => None,
        }
    }
}

/// Reducible job events. Reducers compare both job and generation IDs.
#[derive(Debug, Clone, PartialEq)]
pub(crate) enum AssetJobEvent {
    Queued {
        job_id: AssetJobId,
        slot: AssetJobSlot,
    },
    Started {
        job_id: AssetJobId,
        slot: AssetJobSlot,
    },
    Progress {
        job_id: AssetJobId,
        slot: AssetJobSlot,
        completed: u32,
        total: u32,
    },
    CompileReady {
        job_id: AssetJobId,
        recipe_revision: RevisionId,
        output: Box<AssetCompileOutput>,
    },
    PreviewReady {
        job_id: AssetJobId,
        recipe_revision: RevisionId,
        preview: AssetPreview,
    },
    CandidatesReady {
        job_id: AssetJobId,
        generation_id: AssetGenerationId,
        recipe_revision: RevisionId,
        candidates: Vec<AssetCandidate>,
    },
    CandidatePreviewsReady {
        job_id: AssetJobId,
        generation_id: AssetGenerationId,
        recipe_revision: RevisionId,
        previews: Vec<AssetCandidatePreview>,
        failures: Vec<AssetCandidatePreviewFailure>,
    },
    ExportPackageReady {
        job_id: AssetJobId,
        recipe_revision: RevisionId,
        path: PathBuf,
        package_paths: ModelExportPackagePaths,
    },
    ExportObjReady {
        job_id: AssetJobId,
        recipe_revision: RevisionId,
        path: PathBuf,
        report: GroupedObjReport,
    },
    Failed {
        job_id: AssetJobId,
        message: String,
    },
    Cancelled {
        job_id: AssetJobId,
    },
}

/// Run one asset job on a worker thread.
pub(crate) fn run_asset_job(request: AssetJobRequest) -> Vec<AssetJobEvent> {
    let slot = request.slot();
    let mut events = vec![
        AssetJobEvent::Started {
            job_id: request.job_id,
            slot,
        },
        AssetJobEvent::Progress {
            job_id: request.job_id,
            slot,
            completed: 0,
            total: 1,
        },
    ];

    let final_event = match &request.kind {
        AssetJobKind::CompileCurrentAsset => compile_current(&request),
        AssetJobKind::RenderCurrentPreview {
            artifact,
            camera,
            render_settings,
        } => render_current(
            &request,
            artifact.as_deref(),
            camera.clone(),
            render_settings,
        ),
        AssetJobKind::GenerateCandidates {
            generation_id,
            mode,
            max_candidates,
        } => generate_candidates(&request.recipe, *generation_id, *mode, *max_candidates).map(
            |candidates| AssetJobEvent::CandidatesReady {
                job_id: request.job_id,
                generation_id: *generation_id,
                recipe_revision: request.recipe_revision,
                candidates,
            },
        ),
        AssetJobKind::CompileCandidatePreviews {
            generation_id,
            candidates,
            camera,
            render_settings,
        } => compile_candidate_previews(
            &request,
            *generation_id,
            candidates,
            camera,
            render_settings,
        ),
        AssetJobKind::ExportPackage { path } => export_package(&request, path),
        AssetJobKind::ExportObj { path } => export_obj(&request, path),
    };

    events.push(match final_event {
        Ok(event) => event,
        Err(message) => AssetJobEvent::Failed {
            job_id: request.job_id,
            message,
        },
    });
    events.push(AssetJobEvent::Progress {
        job_id: request.job_id,
        slot,
        completed: 1,
        total: 1,
    });
    events
}

fn compile_current(request: &AssetJobRequest) -> Result<AssetJobEvent, String> {
    let artifact = compile_asset(&request.recipe).map_err(|error| error.to_string())?;
    let config = validation_config_from_recipe(&request.recipe, &artifact);
    let model_validation = validate_model(&artifact, &config);
    let timeline = build_construction_timeline_report(&request.recipe, &artifact);
    Ok(AssetJobEvent::CompileReady {
        job_id: request.job_id,
        recipe_revision: request.recipe_revision,
        output: Box::new(AssetCompileOutput {
            recipe_revision: request.recipe_revision,
            artifact,
            model_validation,
            timeline,
        }),
    })
}

fn render_current(
    request: &AssetJobRequest,
    artifact: Option<&AssetArtifact>,
    camera: Option<OrbitCamera>,
    render_settings: &RenderSettings,
) -> Result<AssetJobEvent, String> {
    let compiled_artifact;
    let artifact = if let Some(artifact) = artifact {
        let hash = recipe_hash(&request.recipe).map_err(|error| error.to_string())?;
        if artifact.source_recipe_hash == hash {
            artifact
        } else {
            compiled_artifact =
                compile_asset(&request.recipe).map_err(|error| error.to_string())?;
            &compiled_artifact
        }
    } else {
        compiled_artifact = compile_asset(&request.recipe).map_err(|error| error.to_string())?;
        &compiled_artifact
    };
    let mesh = preview_mesh_from_artifact(artifact);
    let camera = camera.unwrap_or_else(|| fit_camera_to_bounds(mesh.bounds));
    let image = render_mesh(&mesh, &camera, render_settings).map_err(|error| error.to_string())?;
    Ok(AssetJobEvent::PreviewReady {
        job_id: request.job_id,
        recipe_revision: request.recipe_revision,
        preview: AssetPreview {
            recipe_revision: request.recipe_revision,
            mesh,
            image,
            camera,
        },
    })
}

fn compile_candidate_previews(
    request: &AssetJobRequest,
    generation_id: AssetGenerationId,
    candidates: &[AssetCandidate],
    camera: &OrbitCamera,
    render_settings: &RenderSettings,
) -> Result<AssetJobEvent, String> {
    let mut previews = Vec::with_capacity(candidates.len());
    let mut failures = Vec::new();
    for candidate in candidates {
        match compile_candidate_preview(request, candidate, camera, render_settings) {
            Ok(preview) => previews.push(preview),
            Err(message) => failures.push(AssetCandidatePreviewFailure {
                candidate_id: candidate.id,
                message,
            }),
        }
    }
    Ok(AssetJobEvent::CandidatePreviewsReady {
        job_id: request.job_id,
        generation_id,
        recipe_revision: request.recipe_revision,
        previews,
        failures,
    })
}

fn compile_candidate_preview(
    request: &AssetJobRequest,
    candidate: &AssetCandidate,
    camera: &OrbitCamera,
    render_settings: &RenderSettings,
) -> Result<AssetCandidatePreview, String> {
    let compiled_artifact;
    let artifact = if let Some(artifact) = cached_candidate_artifact(candidate)? {
        artifact
    } else {
        compiled_artifact = compile_asset(&candidate.recipe).map_err(|error| error.to_string())?;
        &compiled_artifact
    };
    let mesh = preview_mesh_from_artifact(artifact);
    let image = render_mesh(&mesh, camera, render_settings).map_err(|error| error.to_string())?;
    Ok(candidate_preview_from_artifact(
        request.recipe_revision,
        candidate,
        artifact,
        image,
        camera.clone(),
    ))
}

fn cached_candidate_artifact(candidate: &AssetCandidate) -> Result<Option<&AssetArtifact>, String> {
    if let Some(artifact) = &candidate.artifact {
        let hash = recipe_hash(&candidate.recipe).map_err(|error| error.to_string())?;
        if artifact.source_recipe_hash == hash {
            return Ok(Some(artifact));
        }
    }
    Ok(None)
}

fn export_package(request: &AssetJobRequest, path: &PathBuf) -> Result<AssetJobEvent, String> {
    let artifact = compile_asset(&request.recipe).map_err(|error| error.to_string())?;
    validate_export_artifact(&request.recipe, &artifact)?;
    let package_paths =
        write_model_package(&request.recipe, &artifact, path).map_err(|error| error.to_string())?;
    Ok(AssetJobEvent::ExportPackageReady {
        job_id: request.job_id,
        recipe_revision: request.recipe_revision,
        path: path.clone(),
        package_paths,
    })
}

fn export_obj(request: &AssetJobRequest, path: &PathBuf) -> Result<AssetJobEvent, String> {
    let artifact = compile_asset(&request.recipe).map_err(|error| error.to_string())?;
    validate_export_artifact(&request.recipe, &artifact)?;
    let export = write_grouped_obj_export(&artifact, Some(&request.recipe))
        .map_err(|error| error.to_string())?;
    fs::write(path, export.obj).map_err(|error| error.to_string())?;
    Ok(AssetJobEvent::ExportObjReady {
        job_id: request.job_id,
        recipe_revision: request.recipe_revision,
        path: path.clone(),
        report: export.report,
    })
}

fn validate_export_artifact(recipe: &AssetRecipe, artifact: &AssetArtifact) -> Result<(), String> {
    let config = validation_config_from_recipe(recipe, artifact);
    let report = validate_model(artifact, &config);
    if artifact.validation_report.is_valid() && report.is_valid() {
        Ok(())
    } else {
        Err("compiled asset failed recipe-derived validation".to_owned())
    }
}

fn generate_candidates(
    recipe: &AssetRecipe,
    generation_id: AssetGenerationId,
    mode: AssetGenerationMode,
    max_candidates: usize,
) -> Result<Vec<AssetCandidate>, String> {
    let max_candidates = max_candidates.max(1);
    let requested_proposals = proposal_count(mode, max_candidates);
    let request = AssetCandidateRequest {
        seed: generation_seed(generation_id, mode),
        proposal_count: requested_proposals,
        result_count: requested_proposals,
        mode: mode.into(),
    };
    let output = generate_asset_candidates(recipe, &request).map_err(|error| error.to_string())?;
    // Relationship selectors are expanded through the compiled artifact so
    // baseline tolerance and candidates use the same recipe-derived policy.
    let (fallback_bounds, baseline_intersection_tolerance) = compile_asset(recipe)
        .map(|artifact| {
            let bounds = preview_mesh_from_artifact(&artifact).bounds;
            let config = validation_config_from_recipe(recipe, &artifact);
            let report = validate_model(&artifact, &config);
            (bounds, report.metrics.accidental_intersection_count as f32)
        })
        .unwrap_or_else(|_| (Aabb::empty(), 0.0));

    let proposals = output
        .candidates
        .into_iter()
        .filter(|candidate| !program_changes_locked_scope(recipe, &candidate.program))
        .collect::<Vec<_>>();
    let compiled =
        compile_search_candidates(proposals, fallback_bounds, baseline_intersection_tolerance);
    let mut candidate_by_id = BTreeMap::<String, (SearchAssetCandidate, AssetArtifact)>::new();
    let mut score_inputs = Vec::with_capacity(compiled.len());
    for compiled in compiled {
        let id = compiled.input.id.clone();
        score_inputs.push(compiled.input);
        if let (Some(candidate), Some(artifact)) = (compiled.candidate, compiled.artifact) {
            candidate_by_id.insert(id, (candidate, artifact));
        }
    }

    let mut policy = AssetSelectionPolicy {
        representative_count: max_candidates,
        duplicate_descriptor_distance: duplicate_descriptor_distance(mode),
        ..AssetSelectionPolicy::default()
    };
    if matches!(mode, AssetGenerationMode::Explore) {
        policy.diversity_weight = 1.25;
    }
    let report = score_and_select_asset_candidates_with_policy(&score_inputs, &policy);

    let mut selected = Vec::with_capacity(max_candidates.min(DEFAULT_GENERATED_CANDIDATES));
    for (slot, scored) in report
        .representatives
        .iter()
        .take(max_candidates)
        .enumerate()
    {
        let Some((candidate, artifact)) = candidate_by_id.remove(&scored.id) else {
            continue;
        };
        selected.push(app_candidate_from_search(
            recipe, candidate, scored, artifact, slot,
        ));
    }
    if selected.is_empty() {
        return Err("no candidates survived semantic scoring".to_owned());
    }
    Ok(selected)
}

fn compile_search_candidates(
    candidates: Vec<SearchAssetCandidate>,
    fallback_bounds: Aabb,
    baseline_intersection_tolerance: f32,
) -> Vec<CompiledSearchCandidate> {
    match proposal_compile_pool() {
        Some(pool) => pool.install(|| {
            candidates
                .into_par_iter()
                .map(|candidate| {
                    compile_search_candidate(
                        candidate,
                        fallback_bounds,
                        baseline_intersection_tolerance,
                    )
                })
                .collect()
        }),
        None => candidates
            .into_iter()
            .map(|candidate| {
                compile_search_candidate(
                    candidate,
                    fallback_bounds,
                    baseline_intersection_tolerance,
                )
            })
            .collect(),
    }
}

fn proposal_compile_pool() -> Option<&'static rayon::ThreadPool> {
    static PROPOSAL_COMPILE_POOL: OnceLock<Option<rayon::ThreadPool>> = OnceLock::new();
    PROPOSAL_COMPILE_POOL
        .get_or_init(|| {
            rayon::ThreadPoolBuilder::new()
                .num_threads(MAX_PROPOSAL_COMPILE_THREADS)
                .build()
                .ok()
        })
        .as_ref()
}

fn compile_search_candidate(
    candidate: SearchAssetCandidate,
    fallback_bounds: Aabb,
    baseline_intersection_tolerance: f32,
) -> CompiledSearchCandidate {
    let id = candidate.id.to_string();
    match compile_asset(&candidate.recipe) {
        Ok(artifact) => {
            let input = scoring_input(
                &id,
                &candidate.recipe,
                &artifact,
                baseline_intersection_tolerance,
            );
            CompiledSearchCandidate {
                input,
                candidate: Some(candidate),
                artifact: Some(artifact),
            }
        }
        Err(_) => {
            let mut input = AssetCandidateInput::new(id.clone(), id, fallback_bounds);
            input.compile_succeeded = false;
            CompiledSearchCandidate {
                input,
                candidate: None,
                artifact: None,
            }
        }
    }
}

impl From<AssetGenerationMode> for AssetCandidateMode {
    fn from(value: AssetGenerationMode) -> Self {
        match value {
            AssetGenerationMode::Refine => Self::Refine,
            AssetGenerationMode::Explore => Self::Explore,
        }
    }
}

fn generation_seed(generation_id: AssetGenerationId, mode: AssetGenerationMode) -> u64 {
    let mode_salt = match mode {
        AssetGenerationMode::Refine => 0x5175_1111_9e37_79b9,
        AssetGenerationMode::Explore => 0x3a8f_2222_85eb_ca6b,
    };
    generation_id.0 ^ mode_salt
}

fn proposal_count(mode: AssetGenerationMode, max_candidates: usize) -> usize {
    let minimum = match mode {
        AssetGenerationMode::Refine => MIN_REFINE_PROPOSALS,
        AssetGenerationMode::Explore => MIN_EXPLORE_PROPOSALS,
    };
    max_candidates
        .saturating_mul(PROPOSAL_MULTIPLIER)
        .max(minimum)
}

fn duplicate_descriptor_distance(mode: AssetGenerationMode) -> f32 {
    match mode {
        AssetGenerationMode::Refine => 0.0,
        AssetGenerationMode::Explore => 0.012,
    }
}

fn app_candidate_from_search(
    parent: &AssetRecipe,
    candidate: SearchAssetCandidate,
    scored: &AssetScoredCandidate,
    artifact: AssetArtifact,
    slot: usize,
) -> AssetCandidate {
    let changed_parameters = changed_parameters(&candidate.program);
    let changes = candidate
        .diagnostics
        .changes
        .iter()
        .map(|diagnostic| candidate_change(parent, diagnostic))
        .collect::<Vec<_>>();
    AssetCandidate {
        id: AssetCandidateId(candidate.id),
        slot,
        label: format!("{} direction {}", mode_label(&candidate.program), slot + 1),
        recipe: candidate.recipe,
        changed_parameters,
        changes,
        quality_penalty: scored.weighted_quality_penalty,
        artifact: Some(artifact),
    }
}

fn mode_label(program: &AssetEditProgram) -> &'static str {
    if program.label.contains("explore") {
        "Explore"
    } else {
        "Refine"
    }
}

fn changed_parameters(program: &AssetEditProgram) -> BTreeSet<ParameterId> {
    program
        .operations
        .iter()
        .filter_map(|operation| match operation {
            AssetEdit::SetScalar { parameter, .. } => Some(*parameter),
            _ => None,
        })
        .collect()
}

fn program_changes_locked_scope(recipe: &AssetRecipe, program: &AssetEditProgram) -> bool {
    program
        .operations
        .iter()
        .any(|operation| operation_changes_locked_scope(recipe, operation))
}

fn operation_changes_locked_scope(recipe: &AssetRecipe, operation: &AssetEdit) -> bool {
    match operation {
        AssetEdit::SetScalar { parameter, .. } => {
            recipe.parameters.get(parameter).is_none_or(|descriptor| {
                recipe.locks.contains(parameter) || parameter_is_locked_by_scope(recipe, descriptor)
            })
        }
        AssetEdit::SetTransform { instance, .. }
        | AssetEdit::SetEnabled { instance, .. }
        | AssetEdit::SetOptionalPartEnabled { instance, .. }
        | AssetEdit::ReplaceInstanceDefinition { instance, .. }
        | AssetEdit::RemoveInstance { instance }
        | AssetEdit::DuplicateInstance { instance, .. }
        | AssetEdit::MirrorInstance { instance, .. }
        | AssetEdit::Attach { instance, .. }
        | AssetEdit::Detach { instance } => instance_locked(recipe, *instance),
        AssetEdit::SetGeneratorDimension { definition, .. }
        | AssetEdit::ReplaceGeometrySource { definition, .. }
        | AssetEdit::SetBevelSettings { definition, .. }
        | AssetEdit::SetSweepProfilePoint { definition, .. }
        | AssetEdit::SetSweepPathFrame { definition, .. }
        | AssetEdit::SetLatheProfilePoint { definition, .. }
        | AssetEdit::SetArrayCount { definition, .. }
        | AssetEdit::SetArraySpacing { definition, .. }
        | AssetEdit::SetTopologyLock { definition, .. } => definition_locked(recipe, *definition),
        AssetEdit::ReplaceDefinition { definition } => definition_locked(recipe, definition.id),
        AssetEdit::AddInstance { instance } => instance
            .parent
            .is_some_and(|parent| instance_locked(recipe, parent)),
        AssetEdit::SetLock { parameter, .. } => recipe.locks.contains(parameter),
        AssetEdit::SetInstanceLock { instance, .. }
        | AssetEdit::SetSubtreeLock { instance, .. } => instance_locked(recipe, *instance),
        AssetEdit::ReorderChildInstances { parent, .. } => {
            parent.is_some_and(|parent| instance_locked(recipe, parent))
        }
    }
}

fn parameter_is_locked_by_scope(
    recipe: &AssetRecipe,
    parameter: &shape_asset::ParameterDescriptor,
) -> bool {
    if let Some(instance) = instance_id_from_scalar_path(&parameter.path) {
        return instance_locked(recipe, instance);
    }
    if let Some(definition) = definition_id_from_scalar_path(&parameter.path) {
        if parameter.topology_changing && recipe.topology_locks.contains(&definition) {
            return true;
        }
        return definition_locked(recipe, definition);
    }
    false
}

fn definition_locked(recipe: &AssetRecipe, definition: PartDefinitionId) -> bool {
    if recipe.topology_locks.contains(&definition) {
        return true;
    }
    let instances = instances_of_definition(recipe, definition);
    !instances.is_empty()
        && instances
            .into_iter()
            .all(|instance| instance_locked(recipe, instance))
}

fn instance_locked(recipe: &AssetRecipe, instance: PartInstanceId) -> bool {
    recipe.instance_locks.contains(&instance)
        || recipe.subtree_locks.iter().any(|root| {
            *root == instance
                || descendants_of(recipe, *root)
                    .map(|descendants| descendants.contains(&instance))
                    .unwrap_or(false)
        })
}

fn candidate_change(
    recipe: &AssetRecipe,
    diagnostic: &AssetChangeDiagnostic,
) -> AssetCandidateChange {
    AssetCandidateChange {
        kind: diagnostic.kind,
        subject: subject_label(recipe, &diagnostic.subject),
        label: change_label(recipe, diagnostic),
        before: clean_diagnostic_value(&diagnostic.before),
        after: clean_diagnostic_value(&diagnostic.after),
        structural: diagnostic.topology_changing,
    }
}

fn subject_label(recipe: &AssetRecipe, subject: &str) -> String {
    if let Some(parameter) = subject.strip_prefix("parameter.")
        && let Ok(id) = parameter.parse::<u64>()
        && let Some(descriptor) = recipe.parameters.get(&ParameterId(id))
    {
        if let Some(instance) = instance_id_from_scalar_path(&descriptor.path)
            && let Some(instance) = recipe.instances.get(&instance)
        {
            return instance.name.clone();
        }
        if let Some(definition) = definition_id_from_scalar_path(&descriptor.path)
            && let Some(definition) = recipe.definitions.get(&definition)
        {
            return definition.name.clone();
        }
        return "Asset".to_owned();
    }
    if let Some(instance) = subject.strip_prefix("instance.")
        && let Ok(id) = instance.parse::<u64>()
        && let Some(instance) = recipe.instances.get(&PartInstanceId(id))
    {
        return instance.name.clone();
    }
    if let Some(definition) = subject.strip_prefix("definition.")
        && let Ok(id) = definition.parse::<u64>()
        && let Some(definition) = recipe.definitions.get(&PartDefinitionId(id))
    {
        return definition.name.clone();
    }
    "Asset".to_owned()
}

fn change_label(recipe: &AssetRecipe, diagnostic: &AssetChangeDiagnostic) -> String {
    if diagnostic.kind == AssetCandidateEditKind::Parameter
        && let Some(parameter) = diagnostic.subject.strip_prefix("parameter.")
        && let Ok(id) = parameter.parse::<u64>()
        && let Some(descriptor) = recipe.parameters.get(&ParameterId(id))
    {
        return descriptor.label.clone();
    }
    match diagnostic.kind {
        AssetCandidateEditKind::Parameter => "parameter".to_owned(),
        AssetCandidateEditKind::Transform => "transform".to_owned(),
        AssetCandidateEditKind::GeneratorDimension => "generator dimension".to_owned(),
        AssetCandidateEditKind::Bevel => "bevel".to_owned(),
        AssetCandidateEditKind::Sweep => "sweep profile".to_owned(),
        AssetCandidateEditKind::Lathe => "lathe profile".to_owned(),
        AssetCandidateEditKind::ArrayCount => "array count".to_owned(),
        AssetCandidateEditKind::ArraySpacing => "array spacing".to_owned(),
        AssetCandidateEditKind::OptionalPart => "optional part".to_owned(),
        AssetCandidateEditKind::Replacement => "replacement".to_owned(),
        AssetCandidateEditKind::DetailDensity => "detail density".to_owned(),
    }
}

fn clean_diagnostic_value(value: &str) -> Option<String> {
    (!value.trim().is_empty() && value != "<missing>" && value != "<unavailable>")
        .then(|| value.to_owned())
}

fn scoring_input(
    id: &str,
    recipe: &AssetRecipe,
    artifact: &AssetArtifact,
    intersection_tolerance: f32,
) -> AssetCandidateInput {
    let mesh = preview_mesh_from_artifact(artifact);
    let validation_config = validation_config_from_recipe(recipe, artifact);
    let model_report = validate_model(artifact, &validation_config);
    let mut input = AssetCandidateInput::new(
        id.to_owned(),
        artifact.source_recipe_hash.to_string(),
        mesh.bounds,
    );
    input.recipe_valid = validate_asset_recipe(recipe).is_valid();
    input.compile_succeeded = true;
    input.requires_closed_part = true;
    input.closed_manifold = model_report.metrics.manifold_closed_part_fraction >= 0.999;
    input.accidental_intersection = model_report.metrics.accidental_intersection_count as f32;
    input.intersection_tolerance = intersection_tolerance.max(0.0);
    input.required_attachment_count = recipe
        .instances
        .values()
        .filter(|instance| instance.attachment.is_some())
        .count();
    let missing_attachments = model_report
        .issues
        .iter()
        .filter(|issue| issue.code == "missing_attachment")
        .count();
    input.attached_attachment_count = input
        .required_attachment_count
        .saturating_sub(missing_attachments);
    input.triangle_count = artifact.statistics.triangle_count as usize;
    input.triangle_budget = ASSET_CANDIDATE_TRIANGLE_BUDGET;
    input.geometry_finite = geometry_is_finite(&mesh) && !has_issue_prefix(artifact, "non_finite");
    input.provenance_complete = model_report.metrics.provenance_coverage >= 0.999
        && !has_issue(artifact, "missing_face_provenance")
        && !has_issue(artifact, "triangle_provenance_count_mismatch");
    let visual = visual_descriptor_for_mesh(&mesh).ok();
    input.volume_approximation =
        mesh_volume(&mesh).unwrap_or_else(|| bounds_volume(mesh.bounds) * 0.55);
    if let Some(visual) = &visual {
        apply_visual_descriptor(&mut input, visual);
    }
    input.part_volumes = artifact
        .compiled_parts
        .iter()
        .map(|part| bounds_volume(part_bounds(part)))
        .collect();
    input.region_count = model_report.metrics.region_count as usize;
    input.detail_count = artifact
        .provenance_report
        .part_region_operation_mappings
        .iter()
        .filter(|mapping| mapping.operation.is_some())
        .count();
    input.symmetry_score = visual
        .as_ref()
        .map_or_else(|| symmetry_score(recipe, artifact), visual_symmetry_score);
    input.repeated_element_count = repeated_element_count(recipe, artifact);
    input.bevel_radii = bevel_radii(recipe);
    input.topology_cost = topology_cost(recipe, artifact);
    input.near_coincident_surface_ratio = near_coincident_ratio(&model_report.issues);
    input.detached_visual_components = recipe.root_instances.len().saturating_sub(1);
    input
}

fn part_bounds(part: &shape_compile::CompiledPart) -> Aabb {
    Aabb {
        min: part.world_mesh.bounds.min.into(),
        max: part.world_mesh.bounds.max.into(),
    }
}

fn has_issue(artifact: &AssetArtifact, code: &str) -> bool {
    artifact
        .validation_report
        .issues
        .iter()
        .any(|issue| issue.code == code)
}

fn has_issue_prefix(artifact: &AssetArtifact, prefix: &str) -> bool {
    artifact
        .validation_report
        .issues
        .iter()
        .any(|issue| issue.code.starts_with(prefix))
}

fn geometry_is_finite(mesh: &TriangleMesh) -> bool {
    mesh.positions
        .iter()
        .all(|position| position.iter().all(|value| value.is_finite()))
        && mesh
            .normals
            .iter()
            .all(|normal| normal.iter().all(|value| value.is_finite()))
        && mesh.bounds.min.is_finite()
        && mesh.bounds.max.is_finite()
}

fn bounds_volume(bounds: Aabb) -> f32 {
    if bounds.is_empty() {
        return 0.0;
    }
    let extent = bounds.extent();
    extent.x.max(0.0) * extent.y.max(0.0) * extent.z.max(0.0)
}

fn apply_visual_descriptor(input: &mut AssetCandidateInput, visual: &MeshVisualDescriptor) {
    input.silhouette_occupancy = visual.silhouette_occupancy;
    input.silhouette_masks = visual
        .silhouette_masks
        .iter()
        .map(|mask| mask.to_vec())
        .collect();
    input.silhouette_perimeter = visual.silhouette_perimeter.to_vec();
    input.depth_histogram = visual
        .depth_histogram
        .iter()
        .flat_map(|histogram| histogram.iter().copied())
        .collect();
}

fn mesh_volume(mesh: &TriangleMesh) -> Option<f32> {
    if mesh.indices.len() < 3 {
        return None;
    }
    let mut volume = 0.0_f32;
    for triangle in mesh.indices.chunks_exact(3) {
        let p0 = mesh.positions.get(triangle[0] as usize)?;
        let p1 = mesh.positions.get(triangle[1] as usize)?;
        let p2 = mesh.positions.get(triangle[2] as usize)?;
        volume += signed_tetrahedron_volume(*p0, *p1, *p2);
    }
    let volume = volume.abs();
    (volume.is_finite() && volume > 1.0e-6).then_some(volume)
}

fn signed_tetrahedron_volume(p0: [f32; 3], p1: [f32; 3], p2: [f32; 3]) -> f32 {
    let cross = [
        p1[1] * p2[2] - p1[2] * p2[1],
        p1[2] * p2[0] - p1[0] * p2[2],
        p1[0] * p2[1] - p1[1] * p2[0],
    ];
    (p0[0] * cross[0] + p0[1] * cross[1] + p0[2] * cross[2]) / 6.0
}

fn visual_symmetry_score(visual: &MeshVisualDescriptor) -> f32 {
    let scores = visual
        .silhouette_masks
        .iter()
        .map(horizontal_mask_symmetry)
        .collect::<Vec<_>>();
    if scores.is_empty() {
        return 0.5;
    }
    (scores.iter().sum::<f32>() / scores.len() as f32).clamp(0.0, 1.0)
}

fn horizontal_mask_symmetry(mask: &[u64; shape_render::VISUAL_DESCRIPTOR_MASK_WORDS]) -> f32 {
    let size = shape_render::VISUAL_DESCRIPTOR_MASK_SIZE as usize;
    let mut compared = 0_usize;
    let mut mismatched = 0_usize;
    for y in 0..size {
        for x in 0..(size / 2) {
            let left = mask_bit(mask, y * size + x);
            let right = mask_bit(mask, y * size + (size - 1 - x));
            if left || right {
                compared += 1;
                if left != right {
                    mismatched += 1;
                }
            }
        }
    }
    if compared == 0 {
        return 0.5;
    }
    1.0 - (mismatched as f32 / compared as f32)
}

fn mask_bit(mask: &[u64; shape_render::VISUAL_DESCRIPTOR_MASK_WORDS], index: usize) -> bool {
    mask.get(index / 64)
        .is_some_and(|word| (word & (1_u64 << (index % 64))) != 0)
}

fn symmetry_score(recipe: &AssetRecipe, artifact: &AssetArtifact) -> f32 {
    let mirrored = recipe.definitions.values().any(|definition| {
        definition
            .geometry
            .operations
            .iter()
            .any(|operation| matches!(operation, ModelingOperationSpec::MirrorInstances { .. }))
    });
    let generated = artifact
        .compiled_parts
        .iter()
        .filter(|part| part.generated_by.is_some())
        .count();
    if mirrored {
        0.9
    } else if generated >= 4 {
        0.75
    } else if generated >= 2 {
        0.6
    } else {
        0.45
    }
}

fn repeated_element_count(recipe: &AssetRecipe, artifact: &AssetArtifact) -> usize {
    let operation_repeats = recipe
        .definitions
        .values()
        .flat_map(|definition| &definition.geometry.operations)
        .map(|operation| match operation {
            ModelingOperationSpec::LinearArray { count, .. }
            | ModelingOperationSpec::RadialArray { count, .. } => count.saturating_sub(1) as usize,
            _ => 0,
        })
        .sum::<usize>();
    operation_repeats
        + artifact
            .compiled_parts
            .iter()
            .filter(|part| part.generated_by.is_some())
            .count()
}

fn bevel_radii(recipe: &AssetRecipe) -> Vec<f32> {
    recipe
        .definitions
        .values()
        .flat_map(|definition| &definition.geometry.operations)
        .filter_map(|operation| match operation {
            ModelingOperationSpec::SetBevelProfile { radius, .. } => Some(*radius),
            _ => None,
        })
        .filter(|radius| radius.is_finite() && *radius > 0.0)
        .collect()
}

fn topology_cost(recipe: &AssetRecipe, artifact: &AssetArtifact) -> f32 {
    let operation_count = recipe
        .definitions
        .values()
        .map(|definition| definition.geometry.operations.len())
        .sum::<usize>() as f32;
    let part_cost = artifact.statistics.part_count as f32 * 0.04;
    let region_cost = artifact
        .provenance_report
        .part_region_operation_mappings
        .len() as f32
        * 0.01;
    (operation_count * 0.05 + part_cost + region_cost).max(0.01)
}

fn near_coincident_ratio(issues: &[shape_compile::validation::ValidationIssue]) -> f32 {
    let count = issues
        .iter()
        .filter(|issue| {
            issue.code.contains("coincident")
                || issue.code.contains("duplicate_vertex")
                || issue.code.contains("minimum_edge")
        })
        .count();
    (count as f32 * 0.02).clamp(0.0, 1.0)
}

fn definition_id_from_scalar_path(path: &str) -> Option<PartDefinitionId> {
    let mut parts = path.split('.');
    (parts.next()? == "definition").then(|| parts.next()?.parse().ok().map(PartDefinitionId))?
}

fn instance_id_from_scalar_path(path: &str) -> Option<PartInstanceId> {
    let mut parts = path.split('.');
    (parts.next()? == "instance").then(|| parts.next()?.parse().ok().map(PartInstanceId))?
}

pub(crate) fn candidate_preview_from_artifact(
    recipe_revision: RevisionId,
    candidate: &AssetCandidate,
    artifact: &AssetArtifact,
    image: RenderedImage,
    camera: OrbitCamera,
) -> AssetCandidatePreview {
    let timeline = build_construction_timeline_report(&candidate.recipe, artifact);
    let validation_summary = validation_summary(&candidate.recipe, artifact);
    AssetCandidatePreview {
        candidate_id: candidate.id,
        recipe_revision,
        thumbnail_rgba: image.rgba8,
        thumbnail_width: image.width,
        thumbnail_height: image.height,
        camera,
        part_count: artifact.statistics.part_count,
        triangle_count: artifact.statistics.triangle_count,
        region_count: artifact
            .provenance_report
            .part_region_operation_mappings
            .iter()
            .filter(|mapping| mapping.region.is_some())
            .count() as u64,
        validation_summary,
        changed_parameters: candidate.changed_parameters.clone(),
        construction_timeline_summary: timeline
            .stages
            .into_iter()
            .map(|stage| stage.summary)
            .collect(),
    }
}

pub(crate) fn preview_mesh_from_artifact(artifact: &AssetArtifact) -> TriangleMesh {
    let mesh = &artifact.combined_preview.mesh;
    TriangleMesh {
        positions: mesh.positions.clone(),
        normals: mesh.normals.clone(),
        indices: mesh.indices.clone(),
        bounds: Aabb {
            min: mesh.bounds.min.into(),
            max: mesh.bounds.max.into(),
        },
    }
}

fn validation_summary(recipe: &AssetRecipe, artifact: &AssetArtifact) -> AssetValidationSummary {
    let config = validation_config_from_recipe(recipe, artifact);
    let report = validate_model(artifact, &config);
    AssetValidationSummary {
        valid: artifact.validation_report.is_valid() && report.is_valid(),
        issue_count: artifact.validation_report.issues.len() + report.issues.len(),
    }
}
