#![forbid(unsafe_code)]

//! Deterministic game-asset-pack export scaffolding.
//!
//! These types describe package sidecars and readiness evidence without taking
//! a dependency on any one runtime, DCC, or mesh export backend.

use std::collections::BTreeSet;
use std::fs;
use std::path::{Component, Path};

use serde::{Deserialize, Serialize};

use crate::surface::{SurfaceArtifact, validate_surface_artifact_with_root};
use crate::{CollisionProxy, GameAssetValidationIssue};

/// Current schema version for static-prop game-ready package manifests.
pub const STATIC_PROP_GAME_READY_PACKAGE_SCHEMA_VERSION: u32 = 1;

/// Current schema version for static-prop readiness validation reports.
pub const STATIC_PROP_READINESS_REPORT_SCHEMA_VERSION: u32 = 1;

/// Runtime-neutral manifest for one static-prop game-readiness package.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StaticPropGameReadyPackage {
    /// Package schema version.
    pub schema_version: u32,
    /// Source Visual Foundry profile slug.
    pub profile_id: String,
    /// Human-facing asset name.
    pub display_name: String,
    /// Human-facing asset family.
    pub asset_family: String,
    /// Stable source recipe hash from the compiled artifact.
    pub source_recipe_hash: u64,
    /// Foundry artifact fingerprint, when generated by Foundry.
    pub artifact_fingerprint: String,
    /// Frozen exact mesh and package artifacts.
    pub frozen_mesh: FrozenMeshArtifact,
    /// Deterministic LOD chain policy and artifact references.
    pub lod_policy: StaticPropLodPolicy,
    /// Material slot assignment policy.
    pub material_slots: Vec<MaterialSlotAssignment>,
    /// UV readiness policy.
    pub uv_policy: UvPolicy,
    /// Concrete surface artifact reference, when emitted.
    #[serde(default)]
    pub surface_artifact: Option<String>,
    /// Collision proxy evidence.
    pub collision: StaticPropCollision,
    /// DCC/runtime handoff evidence.
    pub handoff: StaticPropHandoff,
    /// Visual evidence artifact references.
    pub visual_evidence: StaticPropVisualEvidence,
    /// Manual review marker.
    pub manual_review: ManualReviewMarker,
}

/// Exact frozen model artifacts produced for the package.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FrozenMeshArtifact {
    /// Canonical model-package directory.
    pub canonical_model_package: String,
    /// Canonical asset manifest inside the model package.
    pub asset_manifest: String,
    /// Model-package verification sidecar.
    pub package_verification: String,
    /// Exact grouped OBJ sidecar.
    pub grouped_obj: String,
    /// Blender reconstruction script inside the model package.
    pub blender_reconstruct_script: String,
    /// Whether compile validation passed before packaging.
    pub compile_validation_passed: bool,
    /// Whether model validation passed before packaging.
    pub model_validation_passed: bool,
}

/// LOD policy and emitted artifacts for a static prop.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StaticPropLodPolicy {
    /// Human-facing policy name.
    pub policy: String,
    /// LOD levels in increasing LOD index order.
    pub levels: Vec<StaticPropLodLevel>,
}

/// One static-prop LOD level.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StaticPropLodLevel {
    /// Zero-based LOD index.
    pub index: u32,
    /// Stable level identifier.
    pub id: String,
    /// Source used to create this level.
    pub source: String,
    /// Artifact path for the level.
    pub artifact: String,
    /// Target triangle count for this level.
    pub target_triangle_count: u32,
    /// Whether this LOD is exact source geometry.
    pub exact_source_geometry: bool,
}

/// One material slot assignment.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MaterialSlotAssignment {
    /// Stable material slot key.
    pub slot_id: String,
    /// Human-facing slot name.
    pub display_name: String,
    /// Semantic roles assigned to this slot.
    pub semantic_roles: Vec<String>,
    /// Plain-language policy. This is not a material graph.
    pub policy: String,
    /// Whether the slot contains a final material/texture payload.
    pub material_payload_ready: bool,
}

/// Readiness status for a feature or handoff.
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum StaticPropFeatureStatus {
    /// The feature exists and passed automated validation.
    Ready,
    /// The feature is represented by policy only.
    PolicyOnly,
    /// The feature is not implemented in this package.
    #[default]
    NotImplemented,
    /// Human review is required.
    ManualRequired,
}

/// UV readiness policy.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UvPolicy {
    /// UV feature status.
    pub status: StaticPropFeatureStatus,
    /// Whether UVs are required for a full game-ready claim.
    pub required_for_game_ready: bool,
    /// Stable blocker code when UVs are unavailable.
    pub blocker_code: Option<String>,
    /// Plain-language explanation.
    pub explanation: String,
}

/// Collision proxy evidence.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StaticPropCollision {
    /// Source of the collision proxy.
    pub source: String,
    /// Runtime-neutral collision proxies.
    pub proxies: Vec<CollisionProxy>,
}

/// Handoff evidence for DCC/runtime import.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StaticPropHandoff {
    /// Primary portable package format.
    pub primary_package_format: String,
    /// Blender handoff script path.
    pub blender_handoff_script: String,
    /// Blender handoff status.
    pub blender_status: StaticPropFeatureStatus,
    /// GLB handoff artifact path, when present.
    pub glb_artifact: Option<String>,
    /// GLB handoff status.
    pub glb_status: StaticPropFeatureStatus,
    /// Stable blocker code when GLB is unavailable.
    pub glb_blocker_code: Option<String>,
    /// DCC/runtime import proof artifact, when available.
    #[serde(default)]
    pub engine_import_proof: Option<String>,
    /// Engine/DCC import proof status.
    #[serde(default)]
    pub engine_import_status: StaticPropFeatureStatus,
    /// Engine-native package status.
    #[serde(default)]
    pub engine_native_package_status: StaticPropFeatureStatus,
}

/// Visual evidence artifact references.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StaticPropVisualEvidence {
    /// Front preview PNG.
    pub front: String,
    /// Three-quarter preview PNG.
    pub three_quarter: String,
    /// Side preview PNG.
    pub side: String,
    /// Wireframe preview PNG.
    pub wireframe: String,
    /// Contact-sheet PNG.
    pub contact_sheet: String,
}

/// Manual review status.
#[derive(Debug, Copy, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ManualReviewStatus {
    /// Review has not happened yet.
    Pending,
    /// Review has passed.
    Approved,
    /// Review has rejected the package.
    Rejected,
}

/// Manual review marker for a package.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ManualReviewMarker {
    /// Review status.
    pub status: ManualReviewStatus,
    /// Human reviewer identifier, when available.
    pub reviewer: Option<String>,
    /// Notes or reason.
    pub notes: String,
}

/// Overall readiness status for a static prop package.
#[derive(Debug, Copy, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum StaticPropReadinessStatus {
    /// No blocker was found.
    Ready,
    /// One or more blockers prevent a game-ready claim.
    Blocked,
}

/// One validation check result.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StaticPropReadinessCheck {
    /// Stable check code.
    pub code: String,
    /// Whether this check passed.
    pub passed: bool,
    /// Plain-language explanation.
    pub message: String,
}

/// Static-prop readiness validation report.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StaticPropReadinessReport {
    /// Validation report schema version.
    pub schema_version: u32,
    /// Profile ID copied from the package.
    pub profile_id: String,
    /// Overall status.
    pub status: StaticPropReadinessStatus,
    /// Deterministic validation checks.
    pub checks: Vec<StaticPropReadinessCheck>,
    /// Blocking issues preventing a game-ready claim.
    pub blockers: Vec<GameAssetValidationIssue>,
    /// Non-blocking warnings.
    pub warnings: Vec<GameAssetValidationIssue>,
}

impl StaticPropReadinessReport {
    /// Return true when the package can make a game-ready static-prop claim.
    #[must_use]
    pub fn is_ready(&self) -> bool {
        self.status == StaticPropReadinessStatus::Ready && self.blockers.is_empty()
    }
}

/// Validate a static-prop game-ready package manifest.
#[must_use]
pub fn validate_static_prop_game_ready_package(
    package: &StaticPropGameReadyPackage,
) -> StaticPropReadinessReport {
    validate_static_prop_game_ready_package_inner(package, ArtifactPathValidation::Unverified)
}

/// Validate a static-prop game-ready package manifest and prove referenced
/// artifact paths exist below `package_root`.
#[must_use]
pub fn validate_static_prop_game_ready_package_with_root(
    package: &StaticPropGameReadyPackage,
    package_root: impl AsRef<Path>,
) -> StaticPropReadinessReport {
    validate_static_prop_game_ready_package_inner(
        package,
        ArtifactPathValidation::Filesystem(package_root.as_ref()),
    )
}

fn validate_static_prop_game_ready_package_inner(
    package: &StaticPropGameReadyPackage,
    artifact_paths: ArtifactPathValidation<'_>,
) -> StaticPropReadinessReport {
    let mut builder = StaticPropReadinessReportBuilder::new(&package.profile_id);

    builder.require(
        "schema_version_supported",
        package.schema_version == STATIC_PROP_GAME_READY_PACKAGE_SCHEMA_VERSION,
        Some("schema_version"),
        "unsupported_static_prop_package_schema",
        "Static prop package schema version is supported.",
        "Static prop package schema version is not supported.",
    );
    builder.require_non_empty("profile_id", &package.profile_id, "empty_profile_id");
    builder.require_non_empty("display_name", &package.display_name, "empty_display_name");
    builder.require_non_empty("asset_family", &package.asset_family, "empty_asset_family");
    builder.require(
        "source_recipe_hash_recorded",
        package.source_recipe_hash != 0,
        Some("source_recipe_hash"),
        "missing_source_recipe_hash",
        "Source recipe hash is recorded.",
        "Source recipe hash must be recorded.",
    );
    builder.require_non_empty(
        "artifact_fingerprint",
        &package.artifact_fingerprint,
        "empty_artifact_fingerprint",
    );

    validate_frozen_mesh(&mut builder, &package.frozen_mesh);
    validate_lod_policy(&mut builder, &package.lod_policy);
    validate_material_slots(&mut builder, &package.material_slots);
    validate_uv_policy(&mut builder, &package.uv_policy);
    validate_surface_artifact_ref(&mut builder, package);
    validate_collision(&mut builder, &package.collision);
    validate_handoff(&mut builder, &package.handoff);
    validate_visual_evidence(&mut builder, &package.visual_evidence);
    validate_manual_review(&mut builder, &package.manual_review);
    validate_artifact_paths(&mut builder, package, artifact_paths);

    builder.finish()
}

fn validate_frozen_mesh(builder: &mut StaticPropReadinessReportBuilder, mesh: &FrozenMeshArtifact) {
    builder.require_non_empty(
        "frozen_mesh.canonical_model_package",
        &mesh.canonical_model_package,
        "missing_canonical_model_package",
    );
    builder.require_non_empty(
        "frozen_mesh.asset_manifest",
        &mesh.asset_manifest,
        "missing_asset_manifest",
    );
    builder.require_non_empty(
        "frozen_mesh.package_verification",
        &mesh.package_verification,
        "missing_package_verification",
    );
    builder.require_non_empty(
        "frozen_mesh.grouped_obj",
        &mesh.grouped_obj,
        "missing_grouped_obj",
    );
    builder.require_non_empty(
        "frozen_mesh.blender_reconstruct_script",
        &mesh.blender_reconstruct_script,
        "missing_blender_reconstruct_script",
    );
    builder.require(
        "compile_validation_passed",
        mesh.compile_validation_passed,
        Some("frozen_mesh.compile_validation_passed"),
        "compile_validation_failed",
        "Compiled source artifact passed validation.",
        "Compiled source artifact must pass validation.",
    );
    builder.require(
        "model_validation_passed",
        mesh.model_validation_passed,
        Some("frozen_mesh.model_validation_passed"),
        "model_validation_failed",
        "Frozen model passed model validation.",
        "Frozen model must pass model validation.",
    );
}

fn validate_lod_policy(
    builder: &mut StaticPropReadinessReportBuilder,
    policy: &StaticPropLodPolicy,
) {
    builder.require_non_empty("lod_policy.policy", &policy.policy, "empty_lod_policy");
    builder.require(
        "lod_chain_has_three_levels",
        policy.levels.len() >= 3,
        Some("lod_policy.levels"),
        "insufficient_lod_chain",
        "LOD chain has at least three levels.",
        "LOD chain must include LOD0 plus at least two lower-detail levels.",
    );
    let mut ids = BTreeSet::new();
    let mut artifacts = BTreeSet::new();
    let mut previous_target: Option<u32> = None;
    let mut expected_index = 0_u32;
    for level in &policy.levels {
        builder.require(
            format!("lod_level_{}_index_order", level.index),
            level.index == expected_index,
            Some(format!("lod_policy.levels.{}.index", level.index)),
            "lod_level_order_invalid",
            "LOD level index is in deterministic order.",
            "LOD levels must be ordered from LOD0 upward with no gaps.",
        );
        expected_index = expected_index.saturating_add(1);
        builder.require_non_empty(
            format!("lod_policy.levels.{}.id", level.index),
            &level.id,
            "empty_lod_level_id",
        );
        if !ids.insert(level.id.as_str()) {
            builder.block(
                Some(format!("lod_policy.levels.{}.id", level.index)),
                "duplicate_lod_level_id",
                "LOD level IDs must be unique.",
            );
        }
        if !artifacts.insert(level.artifact.as_str()) {
            builder.block(
                Some(format!("lod_policy.levels.{}.artifact", level.index)),
                "duplicate_lod_artifact",
                "LOD level artifact paths must be unique.",
            );
        }
        builder.require_non_empty(
            format!("lod_policy.levels.{}.source", level.index),
            &level.source,
            "empty_lod_level_source",
        );
        builder.require_non_empty(
            format!("lod_policy.levels.{}.artifact", level.index),
            &level.artifact,
            "missing_lod_artifact",
        );
        builder.require(
            format!("lod_level_{}_triangle_budget", level.index),
            level.target_triangle_count > 0,
            Some(format!(
                "lod_policy.levels.{}.target_triangle_count",
                level.index
            )),
            "invalid_lod_triangle_target",
            "LOD level has a positive triangle target.",
            "LOD triangle targets must be positive.",
        );
        if let Some(previous) = previous_target
            && level.target_triangle_count >= previous
        {
            builder.block(
                Some(format!(
                    "lod_policy.levels.{}.target_triangle_count",
                    level.index
                )),
                "lod_triangle_targets_not_decreasing",
                "LOD triangle targets must decrease as LOD index increases.",
            );
        }
        previous_target = Some(level.target_triangle_count);
        if level.index > 0 && level.exact_source_geometry {
            builder.block(
                Some(format!(
                    "lod_policy.levels.{}.exact_source_geometry",
                    level.index
                )),
                "lower_lod_marked_exact_source",
                "Lower LODs must be lower-detail artifacts, not exact source geometry.",
            );
        }
    }
    if let Some(lod0) = policy.levels.first() {
        builder.require(
            "lod0_exact_source_geometry",
            lod0.exact_source_geometry,
            Some("lod_policy.levels.0.exact_source_geometry"),
            "lod0_not_exact_source",
            "LOD0 is exact source geometry.",
            "LOD0 must be the exact frozen source geometry.",
        );
    }
}

fn validate_material_slots(
    builder: &mut StaticPropReadinessReportBuilder,
    slots: &[MaterialSlotAssignment],
) {
    builder.require(
        "material_slots_present",
        !slots.is_empty(),
        Some("material_slots"),
        "missing_material_slots",
        "Material slots are assigned.",
        "At least one material slot assignment is required.",
    );
    let mut ids = BTreeSet::new();
    for slot in slots {
        builder.require_non_empty(
            format!("material_slots.{}.slot_id", slot.slot_id),
            &slot.slot_id,
            "empty_material_slot_id",
        );
        if !ids.insert(slot.slot_id.as_str()) {
            builder.block(
                Some(format!("material_slots.{}.slot_id", slot.slot_id)),
                "duplicate_material_slot_id",
                "Material slot IDs must be unique.",
            );
        }
        builder.require_non_empty(
            format!("material_slots.{}.display_name", slot.slot_id),
            &slot.display_name,
            "empty_material_slot_display_name",
        );
        builder.require(
            format!("material_slots.{}_semantic_roles", slot.slot_id),
            !slot.semantic_roles.is_empty(),
            Some(format!("material_slots.{}.semantic_roles", slot.slot_id)),
            "material_slot_missing_semantic_roles",
            "Material slot has semantic role coverage.",
            "Material slots must name the semantic roles they cover.",
        );
        builder.require_non_empty(
            format!("material_slots.{}.policy", slot.slot_id),
            &slot.policy,
            "empty_material_slot_policy",
        );
        if !slot.material_payload_ready {
            builder.warn(
                Some(format!("material_slots.{}.material_payload_ready", slot.slot_id)),
                "material_payload_policy_only",
                "Material slot is assigned by policy only; no final material or texture payload is included.",
            );
        }
    }
}

fn validate_uv_policy(builder: &mut StaticPropReadinessReportBuilder, policy: &UvPolicy) {
    builder.require_non_empty(
        "uv_policy.explanation",
        &policy.explanation,
        "empty_uv_explanation",
    );
    builder.require(
        "uv_required_for_game_ready",
        policy.required_for_game_ready,
        Some("uv_policy.required_for_game_ready"),
        "uv_not_required_for_game_ready",
        "UV layout is required for a full static-prop game-ready claim.",
        "UV layout must be required for a full static-prop game-ready claim.",
    );
    if policy.status != StaticPropFeatureStatus::Ready {
        builder.block(
            Some("uv_policy.status"),
            policy
                .blocker_code
                .as_deref()
                .unwrap_or("uv_layout_not_ready"),
            "UV layout is required for a full game-ready static-prop claim.",
        );
    } else {
        builder.pass(
            "uv_policy",
            "UV policy is compatible with the requested claim.",
        );
    }
}

fn validate_surface_artifact_ref(
    builder: &mut StaticPropReadinessReportBuilder,
    package: &StaticPropGameReadyPackage,
) {
    if package.uv_policy.status == StaticPropFeatureStatus::Ready {
        let present = package
            .surface_artifact
            .as_deref()
            .is_some_and(|path| !path.trim().is_empty());
        builder.require(
            "surface_artifact_recorded_for_ready_uvs",
            present,
            Some("surface_artifact"),
            "missing_surface_artifact",
            "Ready UV policy references a concrete surface artifact.",
            "Ready UV policy must reference a concrete surface artifact.",
        );
    }
}

fn validate_artifact_paths(
    builder: &mut StaticPropReadinessReportBuilder,
    package: &StaticPropGameReadyPackage,
    validation: ArtifactPathValidation<'_>,
) {
    let ArtifactPathValidation::Filesystem(root) = validation else {
        builder.block(
            Some("artifact_paths"),
            "artifact_files_not_verified",
            "Artifact paths were not checked against a package directory.",
        );
        return;
    };

    validate_path_exists(
        builder,
        root,
        "frozen_mesh.canonical_model_package",
        &package.frozen_mesh.canonical_model_package,
        ExpectedArtifactPath::Directory,
    );
    validate_path_exists(
        builder,
        root,
        "frozen_mesh.asset_manifest",
        &package.frozen_mesh.asset_manifest,
        ExpectedArtifactPath::File,
    );
    validate_path_exists(
        builder,
        root,
        "frozen_mesh.package_verification",
        &package.frozen_mesh.package_verification,
        ExpectedArtifactPath::File,
    );
    validate_path_exists(
        builder,
        root,
        "frozen_mesh.grouped_obj",
        &package.frozen_mesh.grouped_obj,
        ExpectedArtifactPath::File,
    );
    validate_path_exists(
        builder,
        root,
        "frozen_mesh.blender_reconstruct_script",
        &package.frozen_mesh.blender_reconstruct_script,
        ExpectedArtifactPath::File,
    );
    for level in &package.lod_policy.levels {
        validate_path_exists(
            builder,
            root,
            &format!("lod_policy.levels.{}.artifact", level.index),
            &level.artifact,
            if level.index == 0 {
                ExpectedArtifactPath::Directory
            } else {
                ExpectedArtifactPath::File
            },
        );
    }
    if package.handoff.glb_status == StaticPropFeatureStatus::Ready {
        validate_path_exists(
            builder,
            root,
            "handoff.glb_artifact",
            package.handoff.glb_artifact.as_deref().unwrap_or(""),
            ExpectedArtifactPath::File,
        );
        if package.uv_policy.status == StaticPropFeatureStatus::Ready
            || package.surface_artifact.is_some()
        {
            validate_surface_glb_artifact(
                builder,
                root,
                package.handoff.glb_artifact.as_deref().unwrap_or(""),
                package.surface_artifact.as_deref().unwrap_or(""),
            );
        }
    }
    if let Some(surface_artifact) = package.surface_artifact.as_deref() {
        validate_path_exists(
            builder,
            root,
            "surface_artifact",
            surface_artifact,
            ExpectedArtifactPath::File,
        );
        validate_surface_artifact_payload(builder, package, root, surface_artifact);
    }
    if package.handoff.engine_import_status == StaticPropFeatureStatus::Ready {
        validate_path_exists(
            builder,
            root,
            "handoff.engine_import_proof",
            package.handoff.engine_import_proof.as_deref().unwrap_or(""),
            ExpectedArtifactPath::File,
        );
    }
    validate_path_exists(
        builder,
        root,
        "visual_evidence.front",
        &package.visual_evidence.front,
        ExpectedArtifactPath::File,
    );
    validate_path_exists(
        builder,
        root,
        "visual_evidence.three_quarter",
        &package.visual_evidence.three_quarter,
        ExpectedArtifactPath::File,
    );
    validate_path_exists(
        builder,
        root,
        "visual_evidence.side",
        &package.visual_evidence.side,
        ExpectedArtifactPath::File,
    );
    validate_path_exists(
        builder,
        root,
        "visual_evidence.wireframe",
        &package.visual_evidence.wireframe,
        ExpectedArtifactPath::File,
    );
    validate_path_exists(
        builder,
        root,
        "visual_evidence.contact_sheet",
        &package.visual_evidence.contact_sheet,
        ExpectedArtifactPath::File,
    );
}

fn validate_path_exists(
    builder: &mut StaticPropReadinessReportBuilder,
    root: &Path,
    subject: &str,
    relative_path: &str,
    expected: ExpectedArtifactPath,
) {
    if relative_path.trim().is_empty() {
        return;
    }
    let path = Path::new(relative_path);
    if !is_portable_relative_path(path) {
        builder.block(
            Some(subject.to_owned()),
            "artifact_path_not_portable",
            "Artifact paths must be portable package-relative paths.",
        );
        return;
    }
    let resolved = root.join(path);
    let exists = match expected {
        ExpectedArtifactPath::File => resolved.is_file(),
        ExpectedArtifactPath::Directory => resolved.is_dir(),
    };
    builder.require(
        format!("{}_exists", subject.replace('.', "_")),
        exists,
        Some(subject.to_owned()),
        "artifact_path_missing",
        "Artifact path exists in the package directory.",
        "Artifact path does not exist in the package directory.",
    );
    if exists && expected == ExpectedArtifactPath::File {
        validate_artifact_file_content(builder, subject, relative_path, &resolved);
    }
}

fn validate_surface_artifact_payload(
    builder: &mut StaticPropReadinessReportBuilder,
    package: &StaticPropGameReadyPackage,
    root: &Path,
    relative_path: &str,
) {
    if relative_path.trim().is_empty() {
        return;
    }
    let path = Path::new(relative_path);
    if !is_portable_relative_path(path) {
        return;
    }
    let resolved = root.join(path);
    let Ok(bytes) = fs::read(&resolved) else {
        builder.block(
            Some("surface_artifact"),
            "surface_artifact_unreadable",
            "Surface artifact could not be read for validation.",
        );
        return;
    };
    let Ok(artifact) = serde_json::from_slice::<SurfaceArtifact>(&bytes) else {
        builder.block(
            Some("surface_artifact"),
            "surface_artifact_json_invalid",
            "Surface artifact must be valid Surface Lab artifact JSON.",
        );
        return;
    };
    builder.require(
        "surface_artifact_profile_matches_package",
        artifact.profile_id == package.profile_id,
        Some("surface_artifact.profile_id"),
        "surface_artifact_profile_mismatch",
        "Surface artifact profile matches the static prop package.",
        "Surface artifact profile must match the static prop package.",
    );
    builder.require(
        "surface_artifact_recipe_hash_matches_package",
        artifact.source_recipe_hash == package.source_recipe_hash,
        Some("surface_artifact.source_recipe_hash"),
        "surface_artifact_recipe_hash_mismatch",
        "Surface artifact source recipe hash matches the static prop package.",
        "Surface artifact source recipe hash must match the static prop package.",
    );
    builder.require(
        "surface_artifact_fingerprint_matches_package",
        artifact.source_artifact_fingerprint == package.artifact_fingerprint,
        Some("surface_artifact.source_artifact_fingerprint"),
        "surface_artifact_fingerprint_mismatch",
        "Surface artifact fingerprint matches the static prop package.",
        "Surface artifact fingerprint must match the static prop package.",
    );
    builder.require(
        "surface_artifact_frozen_mesh_matches_package",
        artifact.frozen_mesh_ref == package.frozen_mesh.canonical_model_package,
        Some("surface_artifact.frozen_mesh_ref"),
        "surface_artifact_frozen_mesh_mismatch",
        "Surface artifact frozen mesh reference matches the static prop package.",
        "Surface artifact frozen mesh reference must match the static prop package.",
    );
    let report = validate_surface_artifact_with_root(&artifact, root);
    if report.is_ready() {
        builder.pass(
            "surface_artifact_payload_ready",
            "Surface artifact JSON and referenced payloads passed validation.",
        );
    } else {
        for issue in report.blockers {
            builder.block(
                issue
                    .subject
                    .map(|subject| format!("surface_artifact.{subject}"))
                    .or_else(|| Some("surface_artifact".to_owned())),
                issue.code,
                issue.message,
            );
        }
    }
}

fn validate_surface_glb_artifact(
    builder: &mut StaticPropReadinessReportBuilder,
    root: &Path,
    relative_path: &str,
    expected_surface_artifact_ref: &str,
) {
    if relative_path.trim().is_empty() {
        return;
    }
    let path = Path::new(relative_path);
    if !is_portable_relative_path(path) {
        return;
    }
    let resolved = root.join(path);
    let Ok(bytes) = fs::read(&resolved) else {
        builder.block(
            Some("handoff.glb_artifact"),
            "surface_glb_unreadable",
            "Surface GLB could not be read for validation.",
        );
        return;
    };
    let report = crate::gltf::validate_static_prop_surface_glb_with_artifact_ref(
        &bytes,
        expected_surface_artifact_ref,
    );
    if report.valid {
        builder.pass(
            "surface_glb_payload_ready",
            "Surface GLB includes validated TEXCOORD_0 payload metadata.",
        );
    } else {
        for code in report.issue_codes {
            builder.block(
                Some("handoff.glb_artifact"),
                code,
                "Surface GLB must include a valid TEXCOORD_0 handoff.",
            );
        }
    }
}

fn is_portable_relative_path(path: &Path) -> bool {
    !path.as_os_str().is_empty()
        && path
            .components()
            .all(|component| matches!(component, Component::Normal(_) | Component::CurDir))
}

fn validate_artifact_file_content(
    builder: &mut StaticPropReadinessReportBuilder,
    subject: &str,
    relative_path: &str,
    resolved: &Path,
) {
    let Ok(bytes) = fs::read(resolved) else {
        builder.block(
            Some(subject.to_owned()),
            "artifact_content_unreadable",
            "Artifact content could not be read for validation.",
        );
        return;
    };
    let valid = if relative_path.ends_with(".png") {
        bytes.starts_with(b"\x89PNG\r\n\x1a\n")
    } else if relative_path.ends_with(".obj") {
        let text = String::from_utf8_lossy(&bytes);
        text.lines().any(|line| line.starts_with("v "))
            && text.lines().any(|line| line.starts_with("f "))
    } else if relative_path.ends_with(".glb") {
        crate::gltf::validate_static_prop_glb(&bytes).valid
    } else if relative_path.ends_with(".py") {
        let text = String::from_utf8_lossy(&bytes);
        text.contains("bpy") || text.contains("Blender") || text.contains("Shape Lab")
    } else if relative_path.ends_with("package-verification.json") {
        package_verification_payload_valid(&bytes)
    } else if relative_path.ends_with("asset-manifest.json") {
        asset_manifest_payload_valid(&bytes)
    } else {
        !bytes.is_empty()
    };
    builder.require(
        format!("{}_content_valid", subject.replace('.', "_")),
        valid,
        Some(subject.to_owned()),
        "artifact_content_invalid",
        "Artifact content matches its expected lightweight signature.",
        "Artifact content does not match its expected lightweight signature.",
    );
}

fn package_verification_payload_valid(bytes: &[u8]) -> bool {
    let Ok(value) = serde_json::from_slice::<serde_json::Value>(bytes) else {
        return false;
    };
    value
        .get("checksums_match")
        .and_then(serde_json::Value::as_bool)
        == Some(true)
        && value
            .get("topology_matches_manifest")
            .and_then(serde_json::Value::as_bool)
            == Some(true)
        && value
            .get("finite_numeric_payloads")
            .and_then(serde_json::Value::as_bool)
            == Some(true)
}

fn asset_manifest_payload_valid(bytes: &[u8]) -> bool {
    let Ok(value) = serde_json::from_slice::<serde_json::Value>(bytes) else {
        return false;
    };
    value.get("schema_version").is_some()
        && value.get("files").is_some_and(serde_json::Value::is_object)
        && value.get("parts").is_some_and(serde_json::Value::is_array)
}

#[derive(Debug, Copy, Clone)]
enum ArtifactPathValidation<'a> {
    Unverified,
    Filesystem(&'a Path),
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
enum ExpectedArtifactPath {
    File,
    Directory,
}

fn validate_collision(
    builder: &mut StaticPropReadinessReportBuilder,
    collision: &StaticPropCollision,
) {
    builder.require_non_empty(
        "collision.source",
        &collision.source,
        "empty_collision_source",
    );
    builder.require(
        "collision_proxy_present",
        !collision.proxies.is_empty(),
        Some("collision.proxies"),
        "missing_collision_proxy",
        "At least one collision proxy is present.",
        "A static prop package must include at least one collision proxy.",
    );
    for (index, proxy) in collision.proxies.iter().enumerate() {
        let valid = match proxy {
            CollisionProxy::Box {
                center,
                half_extents,
            } => array_is_finite(center) && array_is_positive(half_extents),
            CollisionProxy::Capsule { a, b, radius } => {
                array_is_finite(a) && array_is_finite(b) && radius.is_finite() && *radius > 0.0
            }
            CollisionProxy::Cylinder {
                center,
                radius,
                height,
            } => {
                array_is_finite(center)
                    && radius.is_finite()
                    && *radius > 0.0
                    && height.is_finite()
                    && *height > 0.0
            }
            CollisionProxy::ConvexHullReserved { reason } => !reason.trim().is_empty(),
        };
        builder.require(
            format!("collision_proxy_{index}_valid"),
            valid,
            Some(format!("collision.proxies.{index}")),
            "invalid_collision_proxy",
            "Collision proxy is finite and non-degenerate.",
            "Collision proxies must be finite and non-degenerate.",
        );
    }
}

fn validate_handoff(builder: &mut StaticPropReadinessReportBuilder, handoff: &StaticPropHandoff) {
    builder.require_non_empty(
        "handoff.primary_package_format",
        &handoff.primary_package_format,
        "empty_primary_package_format",
    );
    builder.require_non_empty(
        "handoff.blender_handoff_script",
        &handoff.blender_handoff_script,
        "missing_blender_handoff_script",
    );
    builder.require(
        "blender_handoff_ready",
        handoff.blender_status == StaticPropFeatureStatus::Ready,
        Some("handoff.blender_status"),
        "blender_handoff_not_ready",
        "Blender handoff script is present.",
        "Blender handoff must be available for this package.",
    );
    if handoff.glb_status != StaticPropFeatureStatus::Ready {
        builder.block(
            Some("handoff.glb_status"),
            handoff
                .glb_blocker_code
                .as_deref()
                .unwrap_or("glb_handoff_not_ready"),
            "Direct GLB handoff is not implemented for this package.",
        );
    } else if handoff
        .glb_artifact
        .as_deref()
        .unwrap_or("")
        .trim()
        .is_empty()
    {
        builder.block(
            Some("handoff.glb_artifact"),
            "missing_glb_artifact",
            "GLB handoff is marked ready but no GLB artifact is referenced.",
        );
    } else {
        builder.pass("glb_handoff_ready", "GLB handoff artifact is present.");
    }
    if handoff.engine_import_status != StaticPropFeatureStatus::Ready {
        builder.block(
            Some("handoff.engine_import_status"),
            "engine_import_proof_missing",
            "DCC/runtime engine import proof is missing.",
        );
    } else if handoff
        .engine_import_proof
        .as_deref()
        .unwrap_or("")
        .trim()
        .is_empty()
    {
        builder.block(
            Some("handoff.engine_import_proof"),
            "engine_import_proof_missing",
            "Engine import proof is marked ready but no proof artifact is referenced.",
        );
    } else {
        builder.pass(
            "engine_import_proof_ready",
            "DCC/runtime import proof is present.",
        );
    }
    if handoff.engine_native_package_status != StaticPropFeatureStatus::Ready {
        builder.block(
            Some("handoff.engine_native_package_status"),
            "engine_native_package_not_implemented",
            "Unity, Unreal, Godot, or other engine-native packages are not implemented.",
        );
    }
}

fn validate_visual_evidence(
    builder: &mut StaticPropReadinessReportBuilder,
    evidence: &StaticPropVisualEvidence,
) {
    builder.require_non_empty(
        "visual_evidence.front",
        &evidence.front,
        "missing_front_preview",
    );
    builder.require_non_empty(
        "visual_evidence.three_quarter",
        &evidence.three_quarter,
        "missing_three_quarter_preview",
    );
    builder.require_non_empty(
        "visual_evidence.side",
        &evidence.side,
        "missing_side_preview",
    );
    builder.require_non_empty(
        "visual_evidence.wireframe",
        &evidence.wireframe,
        "missing_wireframe_preview",
    );
    builder.require_non_empty(
        "visual_evidence.contact_sheet",
        &evidence.contact_sheet,
        "missing_contact_sheet",
    );
}

fn validate_manual_review(
    builder: &mut StaticPropReadinessReportBuilder,
    marker: &ManualReviewMarker,
) {
    builder.require_non_empty(
        "manual_review.notes",
        &marker.notes,
        "empty_manual_review_notes",
    );
    match marker.status {
        ManualReviewStatus::Approved => {
            builder.require(
                "manual_review_reviewer_present",
                marker
                    .reviewer
                    .as_deref()
                    .is_some_and(|reviewer| !reviewer.trim().is_empty()),
                Some("manual_review.reviewer"),
                "missing_manual_reviewer",
                "Manual review includes a reviewer.",
                "Approved manual review must include a reviewer.",
            );
        }
        ManualReviewStatus::Pending => builder.block(
            Some("manual_review.status"),
            "manual_review_pending",
            "Manual game-readiness review has not been completed.",
        ),
        ManualReviewStatus::Rejected => builder.block(
            Some("manual_review.status"),
            "manual_review_rejected",
            "Manual game-readiness review rejected the package.",
        ),
    }
}

fn array_is_finite<const N: usize>(values: &[f32; N]) -> bool {
    values.iter().all(|value| value.is_finite())
}

fn array_is_positive<const N: usize>(values: &[f32; N]) -> bool {
    values.iter().all(|value| value.is_finite() && *value > 0.0)
}

struct StaticPropReadinessReportBuilder {
    profile_id: String,
    checks: Vec<StaticPropReadinessCheck>,
    blockers: Vec<GameAssetValidationIssue>,
    warnings: Vec<GameAssetValidationIssue>,
}

impl StaticPropReadinessReportBuilder {
    fn new(profile_id: &str) -> Self {
        Self {
            profile_id: profile_id.to_owned(),
            checks: Vec::new(),
            blockers: Vec::new(),
            warnings: Vec::new(),
        }
    }

    fn finish(self) -> StaticPropReadinessReport {
        let status = if self.blockers.is_empty() {
            StaticPropReadinessStatus::Ready
        } else {
            StaticPropReadinessStatus::Blocked
        };
        StaticPropReadinessReport {
            schema_version: STATIC_PROP_READINESS_REPORT_SCHEMA_VERSION,
            profile_id: self.profile_id,
            status,
            checks: self.checks,
            blockers: self.blockers,
            warnings: self.warnings,
        }
    }

    fn require(
        &mut self,
        code: impl Into<String>,
        condition: bool,
        subject: Option<impl Into<String>>,
        issue_code: impl Into<String>,
        pass_message: impl Into<String>,
        fail_message: impl Into<String>,
    ) {
        let code = code.into();
        if condition {
            self.checks.push(StaticPropReadinessCheck {
                code,
                passed: true,
                message: pass_message.into(),
            });
        } else {
            let message = fail_message.into();
            self.checks.push(StaticPropReadinessCheck {
                code,
                passed: false,
                message: message.clone(),
            });
            self.blockers.push(GameAssetValidationIssue {
                subject: subject.map(Into::into),
                code: issue_code.into(),
                message,
            });
        }
    }

    fn require_non_empty(
        &mut self,
        subject: impl Into<String>,
        value: &str,
        issue_code: impl Into<String>,
    ) {
        let subject = subject.into();
        let check_code = format!("{}_present", subject.replace('.', "_"));
        self.require(
            check_code,
            !value.trim().is_empty(),
            Some(subject.clone()),
            issue_code,
            format!("{subject} is present."),
            format!("{subject} must be present."),
        );
    }

    fn pass(&mut self, code: impl Into<String>, message: impl Into<String>) {
        self.checks.push(StaticPropReadinessCheck {
            code: code.into(),
            passed: true,
            message: message.into(),
        });
    }

    fn block(
        &mut self,
        subject: Option<impl Into<String>>,
        code: impl Into<String>,
        message: impl Into<String>,
    ) {
        let code = code.into();
        let message = message.into();
        self.checks.push(StaticPropReadinessCheck {
            code: code.clone(),
            passed: false,
            message: message.clone(),
        });
        self.blockers.push(GameAssetValidationIssue {
            subject: subject.map(Into::into),
            code,
            message,
        });
    }

    fn warn(
        &mut self,
        subject: Option<impl Into<String>>,
        code: impl Into<String>,
        message: impl Into<String>,
    ) {
        self.warnings.push(GameAssetValidationIssue {
            subject: subject.map(Into::into),
            code: code.into(),
            message: message.into(),
        });
    }
}
